// Placeholder — will be auto-generated by `supabase gen types` once the schema is deployed.
// See: https://supabase.com/docs/guides/api/rest/generating-types

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
