-- ============================================================
-- Verificación de esquema de MembeGo contra la BD real.
-- Generado desde prisma/baseline/full_schema.sql.
-- Ejecutar en el SQL Editor de Supabase. Si NO devuelve filas,
-- el esquema está completo. Cada fila = un objeto que FALTA.
-- ============================================================
WITH expected_columns(table_name, column_name) AS (
  VALUES
    ('users','id'),
    ('users','supabaseId'),
    ('users','email'),
    ('users','name'),
    ('users','role'),
    ('users','companyId'),
    ('users','createdAt'),
    ('users','updatedAt'),
    ('companies','id'),
    ('companies','name'),
    ('companies','slug'),
    ('companies','type'),
    ('companies','description'),
    ('companies','logoUrl'),
    ('companies','isActive'),
    ('companies','createdAt'),
    ('companies','updatedAt'),
    ('companies','email'),
    ('companies','telefono'),
    ('companies','direccion'),
    ('companies','ciudad'),
    ('companies','categoria'),
    ('companies','website'),
    ('companies','isPublished'),
    ('companies','isFeatured'),
    ('companies','featuredOrder'),
    ('companies','bannerUrl'),
    ('companies','galleryImages'),
    ('companies','provincia'),
    ('companies','pais'),
    ('companies','whatsapp'),
    ('companies','instagram'),
    ('companies','facebook'),
    ('companies','tiktok'),
    ('companies','googleMapsUrl'),
    ('companies','totalMembersCount'),
    ('companies','activePromotionsCount'),
    ('companies','averageRating'),
    ('sucursales','id'),
    ('sucursales','companyId'),
    ('sucursales','nombre'),
    ('sucursales','direccion'),
    ('sucursales','telefono'),
    ('sucursales','activa'),
    ('sucursales','createdAt'),
    ('metodos_pago','id'),
    ('metodos_pago','companyId'),
    ('metodos_pago','tipo'),
    ('metodos_pago','nombre'),
    ('metodos_pago','titular'),
    ('metodos_pago','numeroCuenta'),
    ('metodos_pago','tipoCuenta'),
    ('metodos_pago','instrucciones'),
    ('metodos_pago','activo'),
    ('metodos_pago','createdAt'),
    ('metodos_pago','updatedAt'),
    ('promociones','id'),
    ('promociones','companyId'),
    ('promociones','titulo'),
    ('promociones','descripcion'),
    ('promociones','imagenUrl'),
    ('promociones','vigenciaDesde'),
    ('promociones','vigenciaHasta'),
    ('promociones','activo'),
    ('promociones','publicadaEn'),
    ('promociones','createdAt'),
    ('promociones','updatedAt'),
    ('promociones','slug'),
    ('promociones','tipo'),
    ('promociones','descuento'),
    ('promociones','codigo'),
    ('promociones','isFeatured'),
    ('promociones','featuredOrder'),
    ('promociones','viewCount'),
    ('promociones','shareCount'),
    ('promociones','tags'),
    ('plans','id'),
    ('plans','companyId'),
    ('plans','nombre'),
    ('plans','precio'),
    ('plans','lavadosIncluidos'),
    ('plans','esIlimitado'),
    ('plans','descripcion'),
    ('plans','beneficios'),
    ('plans','vigenciaDias'),
    ('plans','condiciones'),
    ('plans','activo'),
    ('plans','createdAt'),
    ('plans','updatedAt'),
    ('clientes','id'),
    ('clientes','companyId'),
    ('clientes','supabaseId'),
    ('clientes','nombre'),
    ('clientes','telefono'),
    ('clientes','email'),
    ('clientes','fechaNacimiento'),
    ('clientes','avatarUrl'),
    ('clientes','codigoReferido'),
    ('clientes','createdAt'),
    ('clientes','updatedAt'),
    ('referidos','id'),
    ('referidos','companyId'),
    ('referidos','referenteClienteId'),
    ('referidos','referidoClienteId'),
    ('referidos','estado'),
    ('referidos','recompensaAplicada'),
    ('referidos','createdAt'),
    ('referidos','completadoEn'),
    ('reglas_recompensa','id'),
    ('reglas_recompensa','companyId'),
    ('reglas_recompensa','nombre'),
    ('reglas_recompensa','condicion'),
    ('reglas_recompensa','valorCondicion'),
    ('reglas_recompensa','tipoRecompensa'),
    ('reglas_recompensa','valorRecompensa'),
    ('reglas_recompensa','activo'),
    ('reglas_recompensa','createdAt'),
    ('reglas_recompensa','updatedAt'),
    ('whatsapp_config','id'),
    ('whatsapp_config','companyId'),
    ('whatsapp_config','codigoPais'),
    ('whatsapp_config','numero'),
    ('whatsapp_config','mensajePlantilla'),
    ('whatsapp_config','activo'),
    ('whatsapp_config','correoSoporte'),
    ('whatsapp_config','horaInicio'),
    ('whatsapp_config','horaCierre'),
    ('whatsapp_config','diasLaborales'),
    ('whatsapp_config','createdAt'),
    ('whatsapp_config','updatedAt'),
    ('faq_items','id'),
    ('faq_items','companyId'),
    ('faq_items','pregunta'),
    ('faq_items','respuesta'),
    ('faq_items','orden'),
    ('faq_items','activo'),
    ('faq_items','createdAt'),
    ('faq_items','updatedAt'),
    ('support_tickets','id'),
    ('support_tickets','companyId'),
    ('support_tickets','clienteId'),
    ('support_tickets','asunto'),
    ('support_tickets','categoria'),
    ('support_tickets','estado'),
    ('support_tickets','adjuntoUrl'),
    ('support_tickets','createdAt'),
    ('support_tickets','updatedAt'),
    ('ticket_mensajes','id'),
    ('ticket_mensajes','ticketId'),
    ('ticket_mensajes','autorTipo'),
    ('ticket_mensajes','autorNombre'),
    ('ticket_mensajes','cuerpo'),
    ('ticket_mensajes','esNotaInterna'),
    ('ticket_mensajes','createdAt'),
    ('vehiculos','id'),
    ('vehiculos','clienteId'),
    ('vehiculos','marca'),
    ('vehiculos','modelo'),
    ('vehiculos','anio'),
    ('vehiculos','color'),
    ('vehiculos','placa'),
    ('vehiculos','createdAt'),
    ('memberships','id'),
    ('memberships','clienteId'),
    ('memberships','companyId'),
    ('memberships','planId'),
    ('memberships','userId'),
    ('memberships','metodoPagoId'),
    ('memberships','estado'),
    ('memberships','comprobanteUrl'),
    ('memberships','comprobanteNota'),
    ('memberships','rechazadoReason'),
    ('memberships','adminNota'),
    ('memberships','pagoConfirmado'),
    ('memberships','montoPagado'),
    ('memberships','fechaInicio'),
    ('memberships','fechaVencimiento'),
    ('memberships','lavadosRestantes'),
    ('memberships','createdAt'),
    ('memberships','updatedAt'),
    ('qr_tokens','id'),
    ('qr_tokens','clienteId'),
    ('qr_tokens','membresiaId'),
    ('qr_tokens','token'),
    ('qr_tokens','activo'),
    ('qr_tokens','createdAt'),
    ('visits','id'),
    ('visits','clienteId'),
    ('visits','vehiculoId'),
    ('visits','membershipId'),
    ('visits','sucursalId'),
    ('visits','empleadoId'),
    ('visits','servicio'),
    ('visits','descontado'),
    ('visits','fechaVisita'),
    ('visits','notas'),
    ('visits','ipAddress'),
    ('visits','userAgent'),
    ('visits','createdAt'),
    ('comprobantes','id'),
    ('comprobantes','visitId'),
    ('comprobantes','membershipId'),
    ('comprobantes','numero'),
    ('comprobantes','impresiones'),
    ('comprobantes','ultimaImpresion'),
    ('comprobantes','creadoPorId'),
    ('comprobantes','createdAt'),
    ('audit_logs','id'),
    ('audit_logs','companyId'),
    ('audit_logs','userId'),
    ('audit_logs','accion'),
    ('audit_logs','entidadTipo'),
    ('audit_logs','entidadId'),
    ('audit_logs','payload'),
    ('audit_logs','ipAddress'),
    ('audit_logs','userAgent'),
    ('audit_logs','createdAt'),
    ('notificaciones','id'),
    ('notificaciones','userId'),
    ('notificaciones','tipo'),
    ('notificaciones','titulo'),
    ('notificaciones','mensaje'),
    ('notificaciones','href'),
    ('notificaciones','leida'),
    ('notificaciones','createdAt'),
    ('business_categories','id'),
    ('business_categories','name'),
    ('business_categories','slug'),
    ('business_categories','icon'),
    ('business_categories','description'),
    ('business_categories','order'),
    ('business_categories','active'),
    ('business_categories','createdAt'),
    ('business_categories','updatedAt'),
    ('company_to_categories','id'),
    ('company_to_categories','companyId'),
    ('company_to_categories','categoryId'),
    ('company_to_categories','createdAt'),
    ('company_ratings','id'),
    ('company_ratings','companyId'),
    ('company_ratings','clienteId'),
    ('company_ratings','rating'),
    ('company_ratings','comment'),
    ('company_ratings','visible'),
    ('company_ratings','createdAt'),
    ('company_ratings','updatedAt')
),
expected_tables(table_name) AS (
  SELECT DISTINCT table_name FROM expected_columns
),
expected_enums(enum_name, enum_value) AS (
  VALUES
    ('AppRole','SUPERADMIN'),
    ('AppRole','ADMIN_EMPRESA'),
    ('AppRole','EMPLEADO'),
    ('AppRole','CLIENTE'),
    ('AppRole','ADMINISTRADOR'),
    ('AppRole','GERENTE'),
    ('AppRole','CAJERO'),
    ('AppRole','RECEPCION'),
    ('NotifTipo','PAGO_APROBADO'),
    ('NotifTipo','PAGO_RECHAZADO'),
    ('NotifTipo','NUEVO_COMPROBANTE'),
    ('NotifTipo','MEMBRESIA_POR_VENCER'),
    ('NotifTipo','MEMBRESIA_ACTIVADA'),
    ('NotifTipo','PROMOCION_NUEVA'),
    ('NotifTipo','RECOMPENSA_REFERIDO'),
    ('NotifTipo','SISTEMA'),
    ('NotifTipo','TICKET_NUEVO'),
    ('NotifTipo','TICKET_RESPUESTA'),
    ('NotifTipo','TICKET_ACTUALIZADO'),
    ('TicketEstado','NUEVO'),
    ('TicketEstado','EN_PROCESO'),
    ('TicketEstado','ESPERANDO_CLIENTE'),
    ('TicketEstado','RESUELTO'),
    ('TicketEstado','CERRADO'),
    ('TicketCategoria','PAGO'),
    ('TicketCategoria','MEMBRESIA'),
    ('TicketCategoria','BENEFICIOS'),
    ('TicketCategoria','APP'),
    ('TicketCategoria','OTRO'),
    ('TicketAutor','CLIENTE'),
    ('TicketAutor','ADMIN'),
    ('TicketAutor','SISTEMA'),
    ('MembershipEstado','PENDIENTE'),
    ('MembershipEstado','PENDIENTE_PAGO'),
    ('MembershipEstado','RECHAZADA'),
    ('MembershipEstado','ACTIVA'),
    ('MembershipEstado','VENCIDA'),
    ('MembershipEstado','CANCELADA'),
    ('MetodoPagoTipo','TRANSFERENCIA'),
    ('MetodoPagoTipo','PRESENCIAL'),
    ('AuditAccion','VISITA_CONFIRMADA'),
    ('AuditAccion','PAGO_APROBADO'),
    ('AuditAccion','PAGO_RECHAZADO'),
    ('AuditAccion','MEMBRESIA_CANCELADA'),
    ('AuditAccion','MEMBRESIA_RENOVADA'),
    ('AuditAccion','QR_GENERADO'),
    ('AuditAccion','QR_USADO'),
    ('AuditAccion','COMPROBANTE_IMPRESO'),
    ('AuditAccion','REFERIDO_COMPLETADO'),
    ('AuditAccion','RECOMPENSA_OTORGADA'),
    ('AuditAccion','NOTA_INTERNA'),
    ('ReferidoEstado','PENDIENTE'),
    ('ReferidoEstado','COMPLETADO'),
    ('CondicionRecompensa','N_REFERIDOS_COMPLETADOS'),
    ('TipoRecompensa','LAVADOS_GRATIS'),
    ('TipoRecompensa','DESCUENTO_PORCENTAJE'),
    ('TipoRecompensa','DESCUENTO_MONTO')
)
SELECT 'FALTA TABLA' AS tipo, t.table_name AS objeto, NULL::text AS detalle
FROM expected_tables t
LEFT JOIN information_schema.tables it
  ON it.table_schema = 'public' AND it.table_name = t.table_name
WHERE it.table_name IS NULL

UNION ALL
SELECT 'FALTA COLUMNA', ec.table_name, ec.column_name
FROM expected_columns ec
JOIN information_schema.tables it
  ON it.table_schema = 'public' AND it.table_name = ec.table_name
LEFT JOIN information_schema.columns ic
  ON ic.table_schema = 'public' AND ic.table_name = ec.table_name
 AND ic.column_name = ec.column_name
WHERE ic.column_name IS NULL

UNION ALL
SELECT 'FALTA VALOR ENUM', ee.enum_name, ee.enum_value
FROM expected_enums ee
LEFT JOIN (
  SELECT ty.typname AS enum_name, en.enumlabel AS enum_value
  FROM pg_type ty
  JOIN pg_enum en ON en.enumtypid = ty.oid
) actual ON actual.enum_name = ee.enum_name AND actual.enum_value = ee.enum_value
WHERE actual.enum_value IS NULL

ORDER BY tipo, objeto, detalle;
