/**
 * Biblioteca de Automation Playbooks de CAPTACIÓN (Fase E1.1). Estrategias
 * comerciales probadas de adquisición de clientes usadas por plataformas
 * líderes (Klaviyo/HubSpot/Braze/Square), convertidas en playbooks UNIVERSALES
 * instalables sobre el Automation Engine (E1). Reutilizan Rule Engine
 * (condiciones), Action Engine (acciones), Benefit/Promotion/Campaign/Analytics
 * Engines. Car Wash es solo la primera industria que las usa.
 *
 * Cada Playbook es una automatización real (`config`) + su documentación
 * completa. Nada hardcodeado por industria: los beneficios/promos se referencian
 * por código y los textos usan variables `{{...}}`.
 */

import { ACTION_TYPES } from '@/lib/rule-engine'
import { AUTOMATION_EVENTS as EV } from '../domain/events'
import { INDUSTRIES as I } from './types'
import type { AutomationPlaybook } from './types'

const U = I.UNIVERSAL

// Configuración editable mínima (Documento Maestro): común a todos.
const EDITABLE = [
  'nombre', 'descripcion', 'trigger', 'reglas', 'horarios', 'dias', 'fechas',
  'prioridad', 'segmentos', 'beneficios', 'promociones', 'limites', 'expiracion',
  'presupuesto', 'sucursales', 'canales', 'idioma', 'variables',
] as const

// KPIs típicos de captación.
const ACQ_KPIS = [
  'nuevos_leads', 'nuevos_registros', 'tasa_conversion', 'primera_compra',
  'costo_por_adquisicion', 'roi', 'tasa_apertura', 'tasa_clic',
] as const

/** Helper: completa los apartados comunes de un playbook de captación. */
function pb(
  p: Omit<AutomationPlaybook, 'category' | 'editable' | 'kpis' | 'engines'> &
    Partial<Pick<AutomationPlaybook, 'engines' | 'kpis' | 'editable'>>,
): AutomationPlaybook {
  return {
    category: 'captacion',
    editable: p.editable ?? EDITABLE,
    kpis: p.kpis ?? ACQ_KPIS,
    engines: p.engines ?? ['rule', 'action', 'analytics'],
    ...p,
  }
}

export const ACQUISITION_PLAYBOOKS: readonly AutomationPlaybook[] = [
  pb({
    id: 'ACQ-001',
    name: 'Bienvenida con oferta de captación',
    objective: 'Convertir un registro nuevo en su primera compra.',
    problem: 'Los leads se registran pero no compran por falta de un primer incentivo.',
    whenToUse: 'Siempre que un cliente crea cuenta y aún no ha comprado.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['El cliente no tiene compras previas'],
    variables: ['cliente.nombre', 'cliente.segmento'],
    engines: ['rule', 'action', 'benefit', 'analytics'],
    flow: ['Cliente se registra', 'Se entrega un beneficio de bienvenida', 'Se notifica al cliente', 'Se emite evento de recompensa'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_PUSH],
    events: [EV.CLIENT_REWARD_OBTAINED, EV.AUTOMATION_FINISHED],
    exceptions: ['Cliente ya cliente activo', 'Beneficio sin stock'],
    compatibleBenefits: ['CAR-004', 'CAR-011', 'CAR-001'],
    compatiblePromotions: ['CAPTURE', 'FIRST_PURCHASE'],
    compatibleCampaigns: ['bienvenida'],
    dependencies: ['Benefit Engine con un beneficio publicado'],
    compatibleTemplates: ['universal.bienvenida'],
    examples: ['Car Wash: aroma gratis al registrarse', 'Restaurante: postre gratis en la primera visita'],
    notes: 'El beneficio se referencia por código; el texto usa {{cliente.nombre}}.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Entregar bienvenida',
          condition: 'cliente.compras == 0',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-004' }, required: true },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Bienvenido, {{cliente.nombre}}!', body: 'Tienes un regalo de bienvenida.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'ACQ-002',
    name: 'Captura de walk-in por QR',
    objective: 'Registrar y activar a quien llega al local y escanea el QR.',
    problem: 'Los visitantes presenciales no dejan datos ni vuelven.',
    whenToUse: 'Local físico con QR de registro visible.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: cliente registrado (origen QR/local)'],
    conditions: ['Origen del registro = local/QR'],
    variables: ['cliente.nombre', 'cliente.sucursal'],
    engines: ['rule', 'action', 'benefit', 'analytics'],
    flow: ['Visitante escanea QR', 'Se registra', 'Recibe un beneficio inmediato para usar en esa visita'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_WHATSAPP],
    events: [EV.CLIENT_REGISTERED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Registro sin sucursal', 'Cliente existente'],
    compatibleBenefits: ['CAR-003', 'CAR-004'],
    compatiblePromotions: ['CAPTURE'],
    compatibleCampaigns: ['local'],
    dependencies: ['QR de registro por sucursal'],
    compatibleTemplates: [],
    examples: ['Car Wash: aspirado gratis al registrarse en el local'],
    notes: 'El origen se lee de la variable del evento; sin sucursal, cae en excepción.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre', 'cliente.sucursal'],
      channels: ['whatsapp'],
      steps: [
        {
          label: 'Beneficio inmediato',
          condition: 'evento.origen == "qr"',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-003' }, required: true },
            { type: ACTION_TYPES.SEND_WHATSAPP, params: { body: 'Gracias por visitarnos, {{cliente.nombre}}. Úsalo ahora.' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'ACQ-003',
    name: 'Recuperación de registro incompleto',
    objective: 'Recuperar leads que empezaron el registro y no lo terminaron.',
    problem: 'Se pierden leads por fricción o distracción en el alta.',
    whenToUse: 'Cuando existe seguimiento de registros incompletos.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Segmento: lead con registro incompleto'],
    conditions: ['Registro sin completar > 1 hora'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'campaign', 'analytics'],
    flow: ['El lead queda incompleto', 'Se espera', 'Se envía recordatorio con enlace', 'Si completa, se emite evento'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.SEND_WHATSAPP],
    events: [EV.CLIENT_REGISTERED],
    exceptions: ['Lead ya completó', 'Sin correo/teléfono'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['CAPTURE'],
    compatibleCampaigns: ['recuperacion_lead'],
    dependencies: ['Segmentación de registros incompletos (Analytics/Context)'],
    compatibleTemplates: [],
    examples: ['Recordatorio a quien inició el registro y no lo terminó'],
    notes: 'La ventana de espera y el mensaje son editables.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'lead_incompleto' } },
      variables: ['cliente.nombre'],
      channels: ['email', 'whatsapp'],
      limits: { maxPerSubject: 2, perPeriod: 'WEEK' },
      steps: [
        {
          label: 'Recordar completar',
          actions: [
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Te falta un paso, {{cliente.nombre}}' } },
          ],
          wait: { ms: 3_600_000 },
        },
        {
          label: 'Segundo aviso con incentivo',
          actions: [
            { type: ACTION_TYPES.SEND_WHATSAPP, params: { body: 'Completa tu registro y llévate un beneficio.' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'ACQ-004',
    name: 'Entrega de lead magnet',
    objective: 'Captar datos a cambio de un recurso/beneficio de valor.',
    problem: 'Sin incentivo, los visitantes no dejan sus datos.',
    whenToUse: 'Campañas con imán de leads (guía, cupón, sorteo).',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: lead capturado (formulario/landing)'],
    conditions: [],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'benefit', 'campaign', 'analytics'],
    flow: ['El lead deja sus datos', 'Se entrega el imán (cupón/beneficio)', 'Se inicia el nurture'],
    actions: [ACTION_TYPES.CREATE_COUPON, ACTION_TYPES.SEND_EMAIL],
    events: [EV.CLIENT_REGISTERED],
    exceptions: ['Correo inválido', 'Duplicado'],
    compatibleBenefits: ['CAR-011', 'CAR-012'],
    compatiblePromotions: ['CAPTURE'],
    compatibleCampaigns: ['lead_magnet'],
    dependencies: ['Formulario/landing que emita el evento'],
    compatibleTemplates: ['ACQ-005'],
    examples: ['Descarga la guía y recibe 20% en tu primera visita'],
    notes: 'Encadenable con el nurture ACQ-005.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['email'],
      steps: [
        {
          label: 'Entregar imán',
          actions: [
            { type: ACTION_TYPES.CREATE_COUPON, params: { benefitCode: 'CAR-011' }, required: true },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Tu recurso está listo, {{cliente.nombre}}' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'ACQ-005',
    name: 'Secuencia de nurture de nuevos leads',
    objective: 'Convertir leads fríos en primera compra con una serie de toques.',
    problem: 'Un solo mensaje no basta para convertir a un lead nuevo.',
    whenToUse: 'Tras captar un lead que aún no compra.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Sin compras en cada paso'],
    variables: ['cliente.nombre', 'cliente.segmento'],
    engines: ['rule', 'action', 'benefit', 'campaign', 'analytics'],
    flow: ['Bienvenida', 'Espera', 'Prueba social/valor', 'Espera', 'Oferta con urgencia', 'Si compra, termina'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.SEND_PUSH, ACTION_TYPES.APPLY_BENEFIT],
    events: [EV.CLIENT_PURCHASE, EV.AUTOMATION_FINISHED],
    exceptions: ['El cliente compra antes (se corta la secuencia)', 'Baja de canal'],
    compatibleBenefits: ['CAR-011', 'CAR-001'],
    compatiblePromotions: ['FIRST_PURCHASE'],
    compatibleCampaigns: ['nurture'],
    dependencies: ['Benefit Engine', 'Canales de comunicación configurados'],
    compatibleTemplates: ['ACQ-004', 'ACQ-006'],
    examples: ['Serie de 3 correos que termina con oferta de primera compra'],
    notes: 'Cada paso condiciona a que el cliente siga sin comprar; el evento de compra corta el flujo.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['email', 'push'],
      steps: [
        { label: 'Bienvenida', condition: 'cliente.compras == 0', actions: [{ type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Bienvenido, {{cliente.nombre}}' } }], wait: { ms: 172_800_000 } },
        { label: 'Prueba social', condition: 'cliente.compras == 0', actions: [{ type: ACTION_TYPES.SEND_PUSH, params: { title: 'Miles ya confían en nosotros' } }], wait: { ms: 172_800_000 } },
        { label: 'Oferta final', condition: 'cliente.compras == 0', actions: [{ type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-011' }, required: true }, { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Tu descuento vence pronto' } }] },
      ],
    },
  }),

  pb({
    id: 'ACQ-006',
    name: 'Oferta de primera compra con urgencia',
    objective: 'Acelerar la primera compra con un descuento por tiempo limitado.',
    problem: 'Los leads posponen la compra indefinidamente.',
    whenToUse: 'Cuando quieres una conversión rápida tras el registro.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Sin compras', 'Dentro de la ventana de la oferta'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'promotion', 'benefit', 'analytics'],
    flow: ['Registro', 'Se entrega cupón con expiración', 'Recordatorio antes de expirar', 'Si no compra, expira'],
    actions: [ACTION_TYPES.CREATE_COUPON, ACTION_TYPES.SEND_PUSH, ACTION_TYPES.EXPIRE_COUPON],
    events: [EV.CLIENT_COUPON_USED, EV.CLIENT_PURCHASE],
    exceptions: ['Cupón ya usado', 'Fuera de fecha'],
    compatibleBenefits: ['CAR-011', 'CAR-012'],
    compatiblePromotions: ['FIRST_PURCHASE', 'TICKET'],
    compatibleCampaigns: ['urgencia'],
    dependencies: ['Cupón con expiración (Benefit/Promotion Engine)'],
    compatibleTemplates: ['ACQ-005'],
    examples: ['20% en tu primera visita, válido 72 horas'],
    notes: 'La expiración y el % son editables; el recordatorio usa una espera.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['push'],
      steps: [
        { label: 'Entregar cupón', condition: 'cliente.compras == 0', actions: [{ type: ACTION_TYPES.CREATE_COUPON, params: { benefitCode: 'CAR-011', validDays: 3 }, required: true }, { type: ACTION_TYPES.SEND_PUSH, params: { title: '{{cliente.nombre}}, tu 20% vence en 3 días' } }], wait: { ms: 172_800_000 } },
        { label: 'Recordatorio final', condition: 'cliente.compras == 0', actions: [{ type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Última oportunidad!' } }] },
      ],
    },
  }),

  pb({
    id: 'ACQ-007',
    name: 'Bienvenida multicanal',
    objective: 'Maximizar el alcance del primer contacto por varios canales.',
    problem: 'Un solo canal tiene baja tasa de apertura.',
    whenToUse: 'Cuando tienes email, push y WhatsApp habilitados.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: [],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'campaign', 'analytics'],
    flow: ['Registro', 'Envío simultáneo por email + push + WhatsApp'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.SEND_PUSH, ACTION_TYPES.SEND_WHATSAPP],
    events: [EV.AUTOMATION_FINISHED],
    exceptions: ['Sin consentimiento en un canal', 'Datos de contacto faltantes'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['CAPTURE'],
    compatibleCampaigns: ['bienvenida'],
    dependencies: ['Canales configurados y consentimiento del cliente'],
    compatibleTemplates: ['ACQ-001'],
    examples: ['Bienvenida por email, push y WhatsApp a la vez'],
    notes: 'Los canales activos son editables; respeta el consentimiento por canal.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['email', 'push', 'whatsapp'],
      steps: [
        { label: 'Bienvenida multicanal', actions: [
          { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Bienvenido a bordo, {{cliente.nombre}}' } },
          { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Hola, {{cliente.nombre}}!' } },
          { type: ACTION_TYPES.SEND_WHATSAPP, params: { body: 'Gracias por unirte 🎉' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-008',
    name: 'Suscriptor a cliente',
    objective: 'Convertir suscriptores del boletín en compradores.',
    problem: 'Los suscriptores consumen contenido pero no compran.',
    whenToUse: 'Con una base de suscriptores sin primera compra.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Segmento: suscriptor sin compra'],
    conditions: ['Suscrito', 'Sin compras'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'benefit', 'campaign', 'analytics'],
    flow: ['Suscriptor entra al segmento', 'Recibe oferta de primera compra'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_EMAIL],
    events: [EV.CLIENT_PURCHASE],
    exceptions: ['Sin consentimiento de marketing'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['FIRST_PURCHASE'],
    compatibleCampaigns: ['conversion_suscriptor'],
    dependencies: ['Segmento de suscriptores (Analytics)'],
    compatibleTemplates: ['ACQ-006'],
    examples: ['Oferta exclusiva para suscriptores que aún no compran'],
    notes: 'Requiere consentimiento de marketing vigente.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'suscriptor_sin_compra' } },
      variables: ['cliente.nombre'],
      channels: ['email'],
      steps: [
        { label: 'Oferta al suscriptor', condition: 'cliente.compras == 0', actions: [
          { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-011' }, required: true },
          { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Un regalo por seguirnos, {{cliente.nombre}}' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-009',
    name: 'Bienvenida geolocalizada',
    objective: 'Captar clientes cercanos a una sucursal.',
    problem: 'No se aprovecha la proximidad geográfica de nuevos leads.',
    whenToUse: 'Con datos de ciudad/sucursal del lead.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['La ciudad del cliente coincide con una sucursal'],
    variables: ['cliente.ciudad', 'cliente.sucursal'],
    engines: ['rule', 'action', 'benefit', 'analytics'],
    flow: ['Registro', 'Si hay sucursal cercana, invita con beneficio local'],
    actions: [ACTION_TYPES.SEND_WHATSAPP, ACTION_TYPES.APPLY_BENEFIT],
    events: [EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Sin ciudad', 'Sin sucursal en la zona'],
    compatibleBenefits: ['CAR-003', 'CAR-004'],
    compatiblePromotions: ['CAPTURE'],
    compatibleCampaigns: ['local'],
    dependencies: ['Sucursales con ciudad configurada'],
    compatibleTemplates: [],
    examples: ['Visítanos en tu ciudad y recibe un beneficio'],
    notes: 'La coincidencia ciudad↔sucursal se evalúa con una condición del Rule Engine.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.ciudad', 'cliente.sucursal'],
      channels: ['whatsapp'],
      steps: [
        { label: 'Invitación local', condition: 'cliente.tieneSucursalCercana == true', actions: [
          { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-004' }, required: true },
          { type: ACTION_TYPES.SEND_WHATSAPP, params: { body: 'Estamos cerca de ti en {{cliente.ciudad}} 🚗' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-010',
    name: 'Captura por sorteo/concurso',
    objective: 'Generar leads masivos con un sorteo y nutrirlos.',
    problem: 'Falta un gancho para captar volumen de leads.',
    whenToUse: 'Campañas de sorteo/giveaway.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado (participó en sorteo)'],
    conditions: [],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'campaign', 'benefit', 'analytics'],
    flow: ['El lead participa', 'Confirmación de participación', 'Oferta de consolación para todos'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.CREATE_COUPON],
    events: [EV.CLIENT_REGISTERED],
    exceptions: ['Participación duplicada', 'Fuera de fecha del sorteo'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['CAPTURE'],
    compatibleCampaigns: ['sorteo'],
    dependencies: ['Campaña de sorteo (Campaign Engine)'],
    compatibleTemplates: ['ACQ-005'],
    examples: ['Participa por un lavado gratis; todos reciben 15% de descuento'],
    notes: 'El “premio de consolación” convierte a los no ganadores en clientes.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['email'],
      steps: [
        { label: 'Confirmar y ofrecer', actions: [
          { type: ACTION_TYPES.SEND_EMAIL, params: { subject: '¡Estás participando, {{cliente.nombre}}!' } },
          { type: ACTION_TYPES.CREATE_COUPON, params: { benefitCode: 'CAR-011' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-011',
    name: 'Lista de espera a lanzamiento',
    objective: 'Convertir interesados de una waitlist en clientes al abrir.',
    problem: 'Los interesados previos al lanzamiento se enfrían.',
    whenToUse: 'Aperturas de sucursal o lanzamiento de servicio.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: cliente registrado (waitlist)'],
    conditions: [],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'benefit', 'campaign', 'analytics'],
    flow: ['El lead se une a la waitlist', 'Al lanzar, recibe acceso e incentivo prioritario'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.APPLY_BENEFIT],
    events: [EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Waitlist vacía', 'Lanzamiento pospuesto'],
    compatibleBenefits: ['CAR-002', 'CAR-011'],
    compatiblePromotions: ['CAPTURE'],
    compatibleCampaigns: ['lanzamiento'],
    dependencies: ['Segmento waitlist'],
    compatibleTemplates: [],
    examples: ['Acceso anticipado y 25% para la lista de espera'],
    notes: 'Se dispara manualmente o por fecha de lanzamiento.',
    config: {
      trigger: { type: 'DATE', params: { field: 'lanzamiento' } },
      variables: ['cliente.nombre'],
      channels: ['push', 'email'],
      steps: [
        { label: 'Invitar a la waitlist', actions: [
          { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-011' }, required: true },
          { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Ya abrimos, {{cliente.nombre}}!' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-012',
    name: 'Prueba gratis / primer servicio gratis',
    objective: 'Reducir la barrera de entrada con una primera experiencia gratis.',
    problem: 'El precio frena la primera compra de leads dudosos.',
    whenToUse: 'Servicios donde probar convence (alto valor percibido).',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Sin compras previas'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'benefit', 'analytics'],
    flow: ['Registro', 'Se entrega un servicio gratis de prueba', 'Se invita a canjearlo'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_WHATSAPP],
    events: [EV.CLIENT_REWARD_OBTAINED, EV.CLIENT_COUPON_USED],
    exceptions: ['Abuso (múltiples cuentas): usar antifraude del Referral/Analytics'],
    compatibleBenefits: ['CAR-001', 'CAR-003'],
    compatiblePromotions: ['CAPTURE', 'FIRST_PURCHASE'],
    compatibleCampaigns: ['prueba_gratis'],
    dependencies: ['Beneficio de servicio gratis (Benefit Engine)'],
    compatibleTemplates: ['ACQ-006'],
    examples: ['Car Wash: primer lavado gratis', 'Gimnasio: primera clase gratis'],
    notes: 'Limitar a 1 por sujeto; vigilar abuso con reglas antifraude.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['whatsapp'],
      limits: { maxPerSubject: 1, perPeriod: 'EVER' },
      steps: [
        { label: 'Servicio gratis', condition: 'cliente.compras == 0', actions: [
          { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-001' }, required: true },
          { type: ACTION_TYPES.SEND_WHATSAPP, params: { body: 'Tu primer servicio va por nuestra cuenta, {{cliente.nombre}}.' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-013',
    name: 'Oferta estacional de captación',
    objective: 'Captar clientes nuevos en fechas de alta demanda.',
    problem: 'No se aprovechan las temporadas para adquirir clientes.',
    whenToUse: 'Navidad, Black Friday, aniversario, temporada alta.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Horario: durante la temporada'],
    conditions: ['Cliente nuevo', 'Dentro de la fecha de la campaña'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'promotion', 'campaign', 'analytics'],
    flow: ['Inicia la temporada', 'Se ofrece a nuevos leads una promo especial'],
    actions: [ACTION_TYPES.APPLY_DISCOUNT_PERCENT, ACTION_TYPES.SEND_PUSH],
    events: [EV.CLIENT_PURCHASE],
    exceptions: ['Fuera de fecha', 'Cliente existente'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['SEASONAL', 'CAPTURE'],
    compatibleCampaigns: ['navidad', 'black_friday', 'aniversario'],
    dependencies: ['Ventana de fechas configurada'],
    compatibleTemplates: [],
    examples: ['Black Friday: 30% para nuevos clientes'],
    notes: 'Las fechas de inicio/fin y el % son editables.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 9 * * *' },
      variables: ['cliente.nombre'],
      channels: ['push', 'email'],
      schedule: { startAt: null, endAt: null },
      steps: [
        { label: 'Promo de temporada', condition: 'cliente.compras == 0', actions: [
          { type: ACTION_TYPES.APPLY_DISCOUNT_PERCENT, params: { percent: 30 }, required: true },
          { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Oferta de temporada para ti, {{cliente.nombre}}' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-014',
    name: 'Captación por alianza / cross-promo',
    objective: 'Adquirir clientes desde un socio comercial.',
    problem: 'No se convierten los leads que llegan de aliados.',
    whenToUse: 'Convenios y co-marketing con otros negocios.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: cliente registrado (origen socio)'],
    conditions: ['Origen = socio X'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'benefit', 'campaign', 'analytics'],
    flow: ['Lead llega del socio', 'Recibe beneficio de la alianza', 'Se atribuye al socio'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.RECORD_EVENT],
    events: [EV.CLIENT_REGISTERED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Origen no identificado'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['CAPTURE'],
    compatibleCampaigns: ['alianza'],
    dependencies: ['Parámetro de origen/socio en el registro'],
    compatibleTemplates: [],
    examples: ['Clientes referidos por un dealer reciben beneficio de bienvenida'],
    notes: 'La atribución al socio se registra con record_event para el Analytics Engine.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['email'],
      steps: [
        { label: 'Beneficio de alianza', condition: 'evento.origen == "socio"', actions: [
          { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-011' }, required: true },
          { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'captacion.socio' } },
          { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Bienvenido de parte de nuestro aliado' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-015',
    name: 'Retargeting de visitante sin registro',
    objective: 'Recuperar visitantes que vieron la landing y no se registraron.',
    problem: 'La mayoría del tráfico abandona sin dejar datos.',
    whenToUse: 'Con seguimiento de visitantes anónimos identificados luego.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Segmento: visitante identificado sin registro'],
    conditions: ['Visitó la landing', 'Sin registro'],
    variables: [],
    engines: ['rule', 'action', 'campaign', 'analytics'],
    flow: ['Se detecta el visitante', 'Se le impacta con un recordatorio/incentivo'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.SEND_PUSH],
    events: [EV.CLIENT_REGISTERED],
    exceptions: ['Sin datos de contacto', 'Consentimiento faltante'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['CAPTURE'],
    compatibleCampaigns: ['retargeting'],
    dependencies: ['Identificación del visitante (Analytics/Context)'],
    compatibleTemplates: ['ACQ-006'],
    examples: ['Recordatorio a quien vio los planes y no se registró'],
    notes: 'Depende de poder identificar al visitante; respeta privacidad y consentimiento.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'visitante_sin_registro' } },
      channels: ['email', 'push'],
      limits: { maxPerSubject: 2, perPeriod: 'WEEK' },
      steps: [
        { label: 'Recordatorio', actions: [
          { type: ACTION_TYPES.SEND_EMAIL, params: { subject: '¿Terminamos tu registro?' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-016',
    name: 'Reactivación de leads fríos (nunca compraron)',
    objective: 'Convertir leads antiguos que nunca hicieron su primera compra.',
    problem: 'Existe una base de registrados sin ninguna compra.',
    whenToUse: 'Limpieza/activación de la base de leads inactivos.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Horario: revisión periódica'],
    conditions: ['Registrado hace > 30 días', 'Cero compras'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'benefit', 'campaign', 'analytics'],
    flow: ['Se detectan leads fríos', 'Se les ofrece un incentivo fuerte de primera compra'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_WHATSAPP],
    events: [EV.CLIENT_PURCHASE],
    exceptions: ['Ya compró', 'Dado de baja'],
    compatibleBenefits: ['CAR-011', 'CAR-001'],
    compatiblePromotions: ['CAPTURE', 'FIRST_PURCHASE'],
    compatibleCampaigns: ['activacion_leads'],
    dependencies: ['Segmento de leads sin compra (Analytics)'],
    compatibleTemplates: ['ACQ-006'],
    examples: ['Oferta especial a quienes se registraron pero nunca compraron'],
    notes: 'Es captación (aún no son clientes), no recuperación de clientes existentes.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 10 * * 1' },
      variables: ['cliente.nombre'],
      channels: ['whatsapp', 'email'],
      limits: { maxPerSubject: 1, perPeriod: 'MONTH' },
      steps: [
        { label: 'Incentivo fuerte', condition: 'cliente.compras == 0 AND cliente.diasDesdeRegistro > 30', actions: [
          { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-011' }, required: true },
          { type: ACTION_TYPES.SEND_WHATSAPP, params: { body: '{{cliente.nombre}}, tu primera visita con un beneficio especial.' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-017',
    name: 'Club de cumpleaños (captación)',
    objective: 'Captar leads que se unen para recibir un beneficio de cumpleaños.',
    problem: 'Falta un gancho emocional para captar datos.',
    whenToUse: 'Programa “únete y recibe algo en tu cumpleaños”.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: cliente registrado (con fecha de cumpleaños)'],
    conditions: ['Tiene fecha de cumpleaños'],
    variables: ['cliente.nombre', 'cliente.cumpleanos'],
    engines: ['rule', 'action', 'analytics'],
    flow: ['El lead se une al club', 'Confirmación', 'Queda listo para la automatización de cumpleaños'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.RECORD_EVENT],
    events: [EV.CLIENT_REGISTERED],
    exceptions: ['Sin fecha de cumpleaños'],
    compatibleBenefits: ['CAR-014'],
    compatiblePromotions: ['CAPTURE'],
    compatibleCampaigns: ['club_cumpleanos'],
    dependencies: ['Campo de cumpleaños en el registro'],
    compatibleTemplates: ['universal.cumpleanos'],
    examples: ['Únete y recibe un regalo en tu cumpleaños'],
    notes: 'Encadena con la automatización universal de cumpleaños (retención), pero la captación es esta.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre', 'cliente.cumpleanos'],
      channels: ['email'],
      steps: [
        { label: 'Confirmar club', condition: 'cliente.tieneCumpleanos == true', actions: [
          { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Estás en el club, {{cliente.nombre}} 🎂' } },
          { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'captacion.club_cumpleanos' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-018',
    name: 'Prueba social hacia la primera compra',
    objective: 'Usar reseñas/testimonios para empujar la primera compra.',
    problem: 'El lead duda por falta de confianza.',
    whenToUse: 'Tras el registro, si el lead no compra en X días.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Sin compras tras la espera'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'campaign', 'analytics'],
    flow: ['Registro', 'Espera', 'Si no compró, enviar testimonios + oferta suave'],
    actions: [ACTION_TYPES.SEND_EMAIL],
    events: [EV.CLIENT_PURCHASE],
    exceptions: ['Ya compró (se corta)'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['FIRST_PURCHASE'],
    compatibleCampaigns: ['prueba_social'],
    dependencies: ['Contenido de testimonios'],
    compatibleTemplates: ['ACQ-005'],
    examples: ['Correo con reseñas reales 3 días después del registro'],
    notes: 'Complementa el nurture; puede compartir segmento con ACQ-005.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['email'],
      steps: [
        { label: 'Esperar', actions: [], wait: { ms: 259_200_000 } },
        { label: 'Enviar prueba social', condition: 'cliente.compras == 0', actions: [
          { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Lo que dicen nuestros clientes, {{cliente.nombre}}' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-019',
    name: 'Seguimiento de cotización/interés',
    objective: 'Convertir a quien pidió información y no compró.',
    problem: 'Las consultas se enfrían sin seguimiento.',
    whenToUse: 'Cuando el lead solicita precio/información.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente pidió información'],
    conditions: ['Sin compra tras la consulta'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'benefit', 'analytics'],
    flow: ['El lead consulta', 'Espera corta', 'Seguimiento con oferta si no avanzó'],
    actions: [ACTION_TYPES.SEND_WHATSAPP, ACTION_TYPES.APPLY_DISCOUNT_PERCENT],
    events: [EV.CLIENT_PURCHASE],
    exceptions: ['Ya compró', 'Marcó no interesado'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['FIRST_PURCHASE'],
    compatibleCampaigns: ['seguimiento'],
    dependencies: ['Evento de solicitud de información'],
    compatibleTemplates: ['ACQ-006'],
    examples: ['Seguimiento a quien pidió cotización de un plan'],
    notes: 'El disparo por consulta requiere emitir el evento correspondiente.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_PURCHASE },
      variables: ['cliente.nombre'],
      channels: ['whatsapp'],
      steps: [
        { label: 'Seguir la consulta', actions: [], wait: { ms: 86_400_000 } },
        { label: 'Ofrecer cierre', condition: 'cliente.compras == 0', actions: [
          { type: ACTION_TYPES.APPLY_DISCOUNT_PERCENT, params: { percent: 15 } },
          { type: ACTION_TYPES.SEND_WHATSAPP, params: { body: '{{cliente.nombre}}, ¿avanzamos? Te dejamos un 15%.' } },
        ] },
      ],
    },
  }),

  pb({
    id: 'ACQ-020',
    name: 'Combo de primera compra',
    objective: 'Aumentar la conversión con un paquete de bienvenida atractivo.',
    problem: 'Un solo beneficio a veces no basta para convertir.',
    whenToUse: 'Cuando quieres un primer ticket más alto y valioso.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Sin compras'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'benefit', 'promotion', 'analytics'],
    flow: ['Registro', 'Se ofrece un combo/upgrade de bienvenida'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_PUSH],
    events: [EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Combo no disponible'],
    compatibleBenefits: ['CAR-016', 'CAR-002'],
    compatiblePromotions: ['FIRST_PURCHASE', 'TICKET'],
    compatibleCampaigns: ['combo_bienvenida'],
    dependencies: ['Beneficio de upgrade/combo (Benefit Engine)'],
    compatibleTemplates: ['ACQ-001'],
    examples: ['Primera visita: paga básico, llévate premium'],
    notes: 'Usa un beneficio de upgrade (CAR-016) para elevar el valor percibido.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['push'],
      steps: [
        { label: 'Combo de bienvenida', condition: 'cliente.compras == 0', actions: [
          { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-016' }, required: true },
          { type: ACTION_TYPES.SEND_PUSH, params: { title: '{{cliente.nombre}}, tu combo de bienvenida te espera' } },
        ] },
      ],
    },
  }),
]

/** Todas las categorías de playbooks disponibles hasta ahora (E1.1 = captación). */
export function acquisitionPlaybooks(): readonly AutomationPlaybook[] {
  return ACQUISITION_PLAYBOOKS
}

const BY_ID = new Map(ACQUISITION_PLAYBOOKS.map((p) => [p.id, p]))
export function getAcquisitionPlaybook(id: string): AutomationPlaybook | undefined {
  return BY_ID.get(id)
}
