/**
 * Biblioteca de Automation Playbooks de MEMBRESÍAS (Fase E1.6). Automatizan el
 * CICLO DE VIDA COMPLETO de cualquier membresía: creación → activación → primer
 * uso → uso recurrente → cambios → renovación → upgrade/downgrade → suspensión →
 * reactivación → cancelación → expiración → historial. No automatizan un plan
 * concreto (Silver/Gold/…): funcionan con CUALQUIER modelo del Membership Engine
 * (Unlimited, Créditos, Family, Fleet, Corporate, Seasonal, Hybrid, Subscription,
 * Wallet/Prepaid, por niveles, por consumo, personalizada…). Un modelo futuro se
 * integra por configuración, sin cambiar código.
 *
 * Estrategias probadas de suscripción/membresía (Amazon Prime/Costco/gimnasios/
 * SaaS/clubes) convertidas en playbooks UNIVERSALES instalables sobre el
 * Automation Engine (E1). Reutilizan Rule Engine (condiciones), Action Engine
 * (acciones) y el Membership Engine (estado/vigencia/límites), y referencian
 * Benefit/Promotion/Reward/Campaign por código.
 *
 * Cada Playbook es una automatización real (`config`) + su documentación
 * completa (25 apartados, incl. "Tipos de membresías compatibles"). Nada
 * hardcodeado por plan: los beneficios/planes se referencian por variable/código.
 */

import { ACTION_TYPES } from '@/lib/rule-engine'
import { AUTOMATION_EVENTS as EV } from '../domain/events'
import { INDUSTRIES as I, MEMBERSHIP_MODELS as M } from './types'
import type { AutomationPlaybook } from './types'

const U = I.UNIVERSAL
const ANY = M.ANY

// Configuración editable mínima (Documento Maestro): común a todos.
const EDITABLE = [
  'nombre', 'descripcion', 'triggers', 'reglas', 'vigencia', 'renovacion',
  'beneficios', 'promociones', 'prioridad', 'variables', 'horarios', 'segmentos',
  'sucursales', 'canales', 'idioma', 'limites',
] as const

// KPIs típicos del ciclo de vida de membresías.
const MEM_KPIS = [
  'activaciones', 'tasa_renovacion', 'tasa_cancelacion', 'upgrades', 'downgrades',
  'uso_membresia', 'ltv_miembro', 'ingresos_recurrentes', 'reactivaciones',
  'permanencia_promedio', 'tasa_apertura', 'tasa_clic',
] as const

/** Helper: completa los apartados comunes de un playbook de membresías. */
function pb(
  p: Omit<AutomationPlaybook, 'category' | 'editable' | 'kpis' | 'engines' | 'compatibleMembershipModels'> &
    Partial<Pick<AutomationPlaybook, 'engines' | 'kpis' | 'editable' | 'compatibleMembershipModels'>>,
): AutomationPlaybook {
  return {
    category: 'membresias',
    editable: p.editable ?? EDITABLE,
    kpis: p.kpis ?? MEM_KPIS,
    engines: p.engines ?? ['rule', 'action', 'membership', 'analytics'],
    compatibleMembershipModels: p.compatibleMembershipModels ?? [ANY],
    ...p,
  }
}

export const MEMBERSHIP_PLAYBOOKS: readonly AutomationPlaybook[] = [
  pb({
    id: 'MEM-001',
    name: 'Nueva membresía (creación y validaciones)',
    objective: 'Validar y preparar una membresía recién adquirida para activarse.',
    problem: 'Membresías creadas sin validación quedan en un estado ambiguo.',
    whenToUse: 'Cuando el cliente adquiere/crea una membresía.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: membresía creada'],
    conditions: ['Membresía en estado creada', 'Datos y pago válidos'],
    variables: ['cliente.nombre', 'membresia.plan', 'membresia.modelo'],
    engines: ['rule', 'action', 'membership', 'analytics'],
    flow: ['Se crea la membresía', 'Se validan datos/pago/reglas del modelo', 'Se activa', 'Se emite evento de activación'],
    actions: [ACTION_TYPES.ACTIVATE_MEMBERSHIP, ACTION_TYPES.RECORD_EVENT],
    esperas: [],
    events: [EV.MEMBERSHIP_CREATED, EV.MEMBERSHIP_ACTIVATED],
    exceptions: ['Pago pendiente', 'Datos incompletos', 'Reglas del modelo no cumplidas'],
    compatibleMembershipModels: [ANY],
    compatibleBenefits: [],
    compatiblePromotions: ['MEMBERSHIP'],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Membership Engine con validación por modelo'],
    compatibleTemplates: [],
    examples: ['Car Wash: se compra plan ilimitado → validar y activar', 'Gimnasio: alta de plan mensual'],
    notes: 'Las validaciones dependen del modelo; se resuelven en el Membership Engine, no aquí.',
    config: {
      trigger: { type: 'EVENT', event: EV.MEMBERSHIP_CREATED },
      variables: ['cliente.nombre', 'membresia.plan'],
      channels: ['inapp'],
      steps: [
        {
          label: 'Validar y activar',
          actions: [
            { type: ACTION_TYPES.ACTIVATE_MEMBERSHIP, params: { plan: '{{membresia.plan}}' }, required: true },
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'membresia.validada' } },
          ],
          chain: { event: EV.MEMBERSHIP_ACTIVATED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-002',
    name: 'Activación pendiente (recordatorio)',
    objective: 'Lograr que el cliente complete la activación de su membresía.',
    problem: 'Membresías compradas y no activadas no generan uso ni valor.',
    whenToUse: 'Cuando la membresía existe pero sigue sin activarse.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Segmento: membresía sin activar'],
    conditions: ['Membresía creada', 'No activada tras N horas'],
    variables: ['cliente.nombre', 'membresia.plan'],
    engines: ['rule', 'action', 'membership', 'analytics'],
    flow: ['Se detecta activación pendiente', 'Se recuerda activar', 'Al activar, se emite evento'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.SEND_EMAIL],
    esperas: ['Recordatorios a 2h y 24h (editable)'],
    events: [EV.MEMBERSHIP_ACTIVATED],
    exceptions: ['Ya activada', 'Sin canal de contacto'],
    compatibleMembershipModels: [ANY],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['membresias', 'onboarding'],
    dependencies: ['Estado de activación en el Membership Engine'],
    compatibleTemplates: [],
    examples: ['“Tu membresía te espera: actívala para empezar a disfrutar”'],
    notes: 'Cadencia editable; se corta al activar.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'membresia_sin_activar' } },
      variables: ['cliente.nombre', 'membresia.plan'],
      channels: ['push', 'email'],
      limits: { maxPerSubject: 2, perPeriod: 'WEEK' },
      steps: [
        {
          label: 'Recordar activación',
          actions: [{ type: ACTION_TYPES.SEND_PUSH, params: { title: 'Activa tu membresía, {{cliente.nombre}}', body: 'Tu plan {{membresia.plan}} está listo para empezar.' } }],
          chain: { event: EV.MEMBERSHIP_ACTIVATED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-003',
    name: 'Activación con asignación de beneficios iniciales',
    objective: 'Entregar los beneficios iniciales al activarse la membresía.',
    problem: 'Sin beneficios visibles al inicio, el miembro no percibe el valor.',
    whenToUse: 'Justo cuando la membresía se activa.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: membresía activada'],
    conditions: ['Membresía activa', 'Beneficios iniciales definidos por el plan'],
    variables: ['cliente.nombre', 'membresia.plan'],
    engines: ['rule', 'action', 'membership', 'benefit', 'analytics'],
    flow: ['Se activa la membresía', 'Se asignan los beneficios del plan', 'Se comunica al miembro', 'Se registra'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.RECORD_HISTORY],
    esperas: [],
    events: [EV.MEMBERSHIP_ACTIVATED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Plan sin beneficios iniciales', 'Beneficio sin stock'],
    compatibleMembershipModels: [ANY],
    compatibleBenefits: ['CAR-001', 'CAR-004'],
    compatiblePromotions: [],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Membership Engine (beneficios por plan)', 'Benefit Engine'],
    compatibleTemplates: [],
    examples: ['Plan premium → beneficios premium; plan básico → set básico'],
    notes: 'Los beneficios se leen del plan (por código), no se fijan por tipo de plan aquí.',
    config: {
      trigger: { type: 'EVENT', event: EV.MEMBERSHIP_ACTIVATED },
      variables: ['cliente.nombre', 'membresia.plan'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Asignar beneficios del plan',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: '{{membresia.beneficioInicial}}' } },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Bienvenido a tu membresía, {{cliente.nombre}}', body: 'Estos son tus beneficios activos.' } },
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'membresia.beneficios_asignados' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-004',
    name: 'Primer uso de la membresía',
    objective: 'Reforzar el primer consumo y actualizar el historial del miembro.',
    problem: 'El primer uso marca el enganche; sin refuerzo el miembro no repite.',
    whenToUse: 'Cuando el miembro usa por primera vez su membresía.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: primer uso de la membresía'],
    conditions: ['Es el primer uso registrado'],
    variables: ['cliente.nombre', 'membresia.plan'],
    engines: ['rule', 'action', 'membership', 'reward', 'analytics'],
    flow: ['Se detecta el primer uso', 'Se actualiza el historial', 'Se refuerza con reconocimiento', 'Se activan automatizaciones de uso recurrente'],
    actions: [ACTION_TYPES.RECORD_HISTORY, ACTION_TYPES.SEND_PUSH, ACTION_TYPES.ADD_POINTS],
    esperas: [],
    events: [EV.MEMBERSHIP_FIRST_USE, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['No es el primer uso'],
    compatibleMembershipModels: [ANY],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: [],
    compatibleCampaigns: ['membresias', 'onboarding'],
    dependencies: ['Registro de uso en el Membership Engine'],
    compatibleTemplates: [],
    examples: ['“¡Estrenaste tu membresía! Así aprovechas el resto de beneficios”'],
    notes: 'Punto de arranque del uso recurrente; encadena hacia MEM-005.',
    config: {
      trigger: { type: 'EVENT', event: EV.MEMBERSHIP_FIRST_USE },
      variables: ['cliente.nombre'],
      channels: ['push'],
      steps: [
        {
          label: 'Reforzar primer uso',
          actions: [
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'membresia.primer_uso' } },
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 30 } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Estrenaste tu membresía, {{cliente.nombre}}!', body: 'Descubre todo lo que incluye.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-005',
    name: 'Bajo uso de la membresía (evitar cancelación)',
    objective: 'Reactivar el uso cuando el miembro aprovecha poco su plan.',
    problem: 'El bajo uso percibido es la principal causa de no renovar.',
    whenToUse: 'Cuando el uso está por debajo de lo esperado para el plan.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Segmento: membresía con bajo uso'],
    conditions: ['Uso < umbral esperado del plan en el período'],
    variables: ['cliente.nombre', 'membresia.usosPeriodo', 'membresia.usosEsperados'],
    engines: ['rule', 'action', 'membership', 'benefit', 'campaign', 'analytics'],
    flow: ['Se detecta bajo uso', 'Se recuerda el valor del plan', 'Se sugiere cómo aprovecharlo', 'Al usar, se registra'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.SEND_EMAIL],
    esperas: ['Aviso a mitad de período (editable)'],
    events: [EV.CLIENT_BENEFIT_UNDERUSED, EV.CLIENT_VISIT],
    exceptions: ['Uso dentro de lo esperado', 'Plan sin límite de uso'],
    compatibleMembershipModels: [ANY],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['EDUCATIONAL'],
    compatibleCampaigns: ['membresias', 'retencion'],
    dependencies: ['Membership Engine con métricas de uso'],
    compatibleTemplates: [],
    examples: ['“Llevas 1 de 4 lavados este mes: aprovéchalos antes de que termine”'],
    notes: 'El umbral esperado depende del modelo (créditos, ilimitado, etc.), configurable.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'membresia_bajo_uso' } },
      variables: ['cliente.nombre', 'membresia.usosPeriodo', 'membresia.usosEsperados'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Recordar valor del plan',
          condition: 'membresia.usosPeriodo < membresia.usosEsperados',
          actions: [{ type: ACTION_TYPES.SEND_PUSH, params: { title: 'Aprovecha tu membresía, {{cliente.nombre}}', body: 'Te quedan usos este período. No los pierdas.' } }],
          chain: { event: EV.CLIENT_VISIT },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-006',
    name: 'Sobreutilización (oportunidad de upgrade)',
    objective: 'Ofrecer un plan superior a quien satura su membresía actual.',
    problem: 'Un miembro que agota su plan repetidamente podría pagar más y estar mejor.',
    whenToUse: 'Cuando el uso supera consistentemente el límite del plan.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Segmento: membresía sobreutilizada'],
    conditions: ['Uso >= límite del plan de forma recurrente'],
    variables: ['cliente.nombre', 'membresia.usosPeriodo', 'membresia.limite'],
    engines: ['rule', 'action', 'membership', 'promotion', 'analytics'],
    flow: ['Se detecta sobreuso', 'Se recomienda un upgrade con mejor relación de valor', 'Al mejorar, se emite evento'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_EMAIL],
    esperas: [],
    events: [EV.MEMBERSHIP_UPGRADED, EV.AUTOMATION_FINISHED],
    exceptions: ['Ya está en el plan superior', 'Sin plan superior disponible'],
    compatibleMembershipModels: [M.CREDITS, M.TIER, M.HYBRID, M.PAY_PER_VISIT, M.SUBSCRIPTION_BOX, M.CUSTOM],
    compatibleBenefits: [],
    compatiblePromotions: ['UPGRADE'],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Membership Engine con límites y planes superiores'],
    compatibleTemplates: [],
    examples: ['Créditos agotados cada mes → sugerir plan ilimitado'],
    notes: 'Aplica a modelos con límite; el upgrade lo calcula el Membership Engine.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'membresia_sobreuso' } },
      variables: ['cliente.nombre', 'membresia.usosPeriodo', 'membresia.limite'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Recomendar upgrade',
          condition: 'membresia.usosPeriodo >= membresia.limite',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'membership', action: 'recommend_upgrade' } },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Un plan mejor para ti, {{cliente.nombre}}', body: 'Usas mucho tu membresía: con otro plan ahorrarías.' } },
          ],
          chain: { event: EV.MEMBERSHIP_UPGRADED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-007',
    name: 'Renovación próxima (recordatorios escalonados)',
    objective: 'Maximizar renovaciones avisando antes del vencimiento.',
    problem: 'Muchas membresías vencen por falta de un aviso oportuno.',
    whenToUse: 'Cuando se acerca la fecha de vencimiento.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: membresía por vencer'],
    conditions: ['Vencimiento dentro de la ventana', 'Sin renovación aún'],
    variables: ['cliente.nombre', 'membresia.diasParaVencer', 'membresia.plan'],
    engines: ['rule', 'action', 'membership', 'benefit', 'analytics'],
    flow: ['Se acerca el vencimiento', 'Recordatorios a 15/7/1 días', 'Opción de renovar con incentivo', 'Al renovar, se registra'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.SEND_PUSH],
    esperas: ['Recordatorios a 15, 7 y 1 días antes (editable)'],
    events: [EV.MEMBERSHIP_EXPIRING, EV.MEMBERSHIP_RENEWED],
    exceptions: ['Ya renovó', 'Renovación automática activa (usar MEM-008)'],
    compatibleMembershipModels: [ANY],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['RENEWAL'],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Membership Engine con fecha de vencimiento'],
    compatibleTemplates: [],
    examples: ['“Tu plan vence en 7 días: renueva y sigue disfrutando”'],
    notes: 'Ventana y número de recordatorios editables; no aplica a auto-renovación.',
    config: {
      trigger: { type: 'EVENT', event: EV.MEMBERSHIP_EXPIRING },
      variables: ['cliente.nombre', 'membresia.diasParaVencer', 'membresia.plan'],
      channels: ['email', 'push', 'whatsapp'],
      steps: [
        {
          label: 'Recordatorio de renovación',
          actions: [{ type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Tu membresía vence pronto, {{cliente.nombre}}', body: 'Renueva tu {{membresia.plan}} en un clic.' } }],
          chain: { event: EV.MEMBERSHIP_RENEWED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-008',
    name: 'Renovación automática (confirmación y aviso)',
    objective: 'Ejecutar la auto-renovación con transparencia y sin fricción.',
    problem: 'Las auto-renovaciones sin aviso generan disputas y cancelaciones.',
    whenToUse: 'Cuando el plan tiene renovación automática activada.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: membresía por vencer (auto-renovación)'],
    conditions: ['Auto-renovación activa', 'Método de pago válido'],
    variables: ['cliente.nombre', 'membresia.plan', 'membresia.fechaRenovacion'],
    engines: ['rule', 'action', 'membership', 'analytics'],
    flow: ['Aviso previo de auto-renovación', 'Se renueva automáticamente', 'Se confirma', 'Se registra en el historial'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.RENEW_MEMBERSHIP, ACTION_TYPES.RECORD_HISTORY],
    esperas: ['Aviso previo (ej. 3 días antes) editable'],
    events: [EV.MEMBERSHIP_RENEWED],
    exceptions: ['Auto-renovación desactivada', 'Pago fallido (deriva a dunning)'],
    compatibleMembershipModels: [M.SUBSCRIPTION_BOX, M.UNLIMITED, M.TIER, M.PREMIUM, M.VIP, M.CORPORATE, M.CUSTOM],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Membership Engine con auto-renovación y cobros'],
    compatibleTemplates: [],
    examples: ['SaaS/suscripción: aviso previo + cobro automático + recibo'],
    notes: 'Prioriza transparencia (aviso previo); si el pago falla, encadena a MEM-016.',
    config: {
      trigger: { type: 'EVENT', event: EV.MEMBERSHIP_EXPIRING },
      variables: ['cliente.nombre', 'membresia.plan', 'membresia.fechaRenovacion'],
      channels: ['email'],
      steps: [
        {
          label: 'Aviso previo',
          condition: 'membresia.autoRenovacion == true',
          actions: [{ type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Tu membresía se renovará el {{membresia.fechaRenovacion}}', body: '{{cliente.nombre}}, tu plan {{membresia.plan}} se renovará automáticamente.' } }],
          wait: { ms: 259_200_000 },
        },
        {
          label: 'Renovar y confirmar',
          condition: 'membresia.autoRenovacion == true',
          actions: [
            { type: ACTION_TYPES.RENEW_MEMBERSHIP, params: { plan: '{{membresia.plan}}' }, required: true },
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'membresia.auto_renovada' } },
          ],
          chain: { event: EV.MEMBERSHIP_RENEWED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-009',
    name: 'Renovación anticipada con incentivo',
    objective: 'Adelantar ingresos premiando la renovación temprana.',
    problem: 'Sin incentivo, nadie renueva antes de tiempo.',
    whenToUse: 'Antes del vencimiento, para ofrecer renovar ya con beneficio.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Segmento: renovación anticipada elegible'],
    conditions: ['Membresía activa', 'Dentro de la ventana de renovación anticipada'],
    variables: ['cliente.nombre', 'membresia.plan'],
    engines: ['rule', 'action', 'membership', 'benefit', 'promotion', 'analytics'],
    flow: ['Se ofrece renovar antes con incentivo', 'Al renovar anticipadamente, se aplica el beneficio', 'Se registra'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.APPLY_DISCOUNT_PERCENT, ACTION_TYPES.RENEW_MEMBERSHIP],
    esperas: ['Ventana de anticipación editable'],
    events: [EV.MEMBERSHIP_RENEWED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Fuera de ventana', 'Ya renovó'],
    compatibleMembershipModels: [ANY],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['EARLY_RENEWAL'],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Membership Engine con renovación anticipada'],
    compatibleTemplates: [],
    examples: ['“Renueva ahora y llévate 1 mes extra / 15% de descuento”'],
    notes: 'El incentivo y la ventana son editables; mejora el flujo de caja.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'renovacion_anticipada' } },
      variables: ['cliente.nombre', 'membresia.plan'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Ofrecer renovación anticipada',
          actions: [
            { type: ACTION_TYPES.APPLY_DISCOUNT_PERCENT, params: { percent: 15 } },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Renueva antes y ahorra, {{cliente.nombre}}', body: 'Adelanta tu renovación con un beneficio exclusivo.' } },
          ],
          chain: { event: EV.MEMBERSHIP_RENEWED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-010',
    name: 'Upgrade sugerido (oportunidad de mejora)',
    objective: 'Detectar y recomendar mejoras de plan con migración de beneficios.',
    problem: 'Los miembros no descubren planes superiores que les convendrían.',
    whenToUse: 'Cuando el comportamiento sugiere que un plan mayor aporta más valor.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Segmento: candidato a upgrade'],
    conditions: ['Patrón de uso/gasto indica beneficio de un plan superior'],
    variables: ['cliente.nombre', 'membresia.plan', 'membresia.planSugerido'],
    engines: ['rule', 'action', 'membership', 'benefit', 'promotion', 'analytics'],
    flow: ['Se detecta oportunidad', 'Se recomienda el upgrade', 'Se migran beneficios y se conserva el historial', 'Se registra'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.UPDATE_MEMBERSHIP_LEVEL, ACTION_TYPES.RECORD_HISTORY],
    esperas: [],
    events: [EV.MEMBERSHIP_UPGRADED, EV.CLIENT_LEVEL_UP],
    exceptions: ['Sin plan superior', 'Ya en el máximo'],
    compatibleMembershipModels: [M.TIER, M.HYBRID, M.PREMIUM, M.VIP, M.CREDITS, M.SUBSCRIPTION_BOX, M.CUSTOM],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['UPGRADE'],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Membership Engine con migración de beneficios e historial'],
    compatibleTemplates: [],
    examples: ['“Con el plan Plus tendrías estos beneficios extra”'],
    notes: 'La migración de beneficios y el historial los gestiona el Membership Engine.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'candidato_upgrade' } },
      variables: ['cliente.nombre', 'membresia.planSugerido'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Sugerir upgrade',
          actions: [
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Una mejora pensada para ti, {{cliente.nombre}}', body: 'El plan {{membresia.planSugerido}} se ajusta mejor a tu uso.' } },
          ],
          chain: { event: EV.MEMBERSHIP_UPGRADED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-011',
    name: 'Downgrade solicitado (retener con reglas)',
    objective: 'Procesar un downgrade aplicando reglas y ofreciendo alternativas.',
    problem: 'Un downgrade mal gestionado se convierte en cancelación total.',
    whenToUse: 'Cuando el miembro solicita bajar de plan.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: downgrade solicitado'],
    conditions: ['Solicitud de downgrade', 'Reglas de cambio aplicables'],
    variables: ['cliente.nombre', 'membresia.plan', 'membresia.planDestino'],
    engines: ['rule', 'action', 'membership', 'benefit', 'campaign', 'analytics'],
    flow: ['Se recibe la solicitud', 'Se ofrece alternativa/retención', 'Si procede, se aplica el downgrade y se ajustan beneficios', 'Se registra el cambio'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.UPDATE_MEMBERSHIP_LEVEL, ACTION_TYPES.RECORD_HISTORY],
    esperas: ['Oferta de retención antes de aplicar (editable)'],
    events: [EV.MEMBERSHIP_DOWNGRADED, EV.AUTOMATION_FINISHED],
    exceptions: ['Sin plan inferior', 'Reglas no permiten el cambio ahora'],
    compatibleMembershipModels: [M.TIER, M.HYBRID, M.PREMIUM, M.VIP, M.CREDITS, M.CUSTOM],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['RETENTION'],
    compatibleCampaigns: ['membresias', 'retencion'],
    dependencies: ['Membership Engine con reglas de downgrade'],
    compatibleTemplates: [],
    examples: ['“Antes de bajar de plan, ¿probamos esto?” → si insiste, se aplica'],
    notes: 'Intenta retención antes del downgrade; el ajuste de beneficios lo hace el motor.',
    config: {
      trigger: { type: 'EVENT', event: EV.MEMBERSHIP_DOWNGRADED },
      variables: ['cliente.nombre', 'membresia.planDestino'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Ofrecer retención',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-011' } },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Antes de cambiar tu plan, {{cliente.nombre}}', body: 'Tenemos una alternativa que quizá te convenga.' } },
          ],
        },
        {
          label: 'Aplicar downgrade',
          actions: [
            { type: ACTION_TYPES.UPDATE_MEMBERSHIP_LEVEL, params: { level: '{{membresia.planDestino}}' } },
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'membresia.downgrade_aplicado' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'MEM-012',
    name: 'Suspensión temporal (freeze)',
    objective: 'Permitir pausar la membresía conservando el historial y el vínculo.',
    problem: 'Sin opción de pausa, el miembro cancela definitivamente.',
    whenToUse: 'Cuando el miembro solicita o califica para una pausa temporal.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: membresía suspendida'],
    conditions: ['Solicitud/condición de suspensión', 'Reglas de freeze aplicables'],
    variables: ['cliente.nombre', 'membresia.plan', 'membresia.fechaReanudacion'],
    engines: ['rule', 'action', 'membership', 'analytics'],
    flow: ['Se suspende la membresía', 'Se conserva historial y beneficios acumulados', 'Se programa el recordatorio de reactivación', 'Se registra'],
    actions: [ACTION_TYPES.FREEZE_MEMBERSHIP, ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.RECORD_HISTORY],
    esperas: ['Recordatorio antes de la fecha de reanudación (editable)'],
    events: [EV.MEMBERSHIP_SUSPENDED],
    exceptions: ['Plan no admite suspensión', 'Ya suspendida'],
    compatibleMembershipModels: [M.UNLIMITED, M.TIER, M.PREMIUM, M.SUBSCRIPTION_BOX, M.SEASONAL, M.CORPORATE, M.CUSTOM],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Membership Engine con freeze/reanudación'],
    compatibleTemplates: [],
    examples: ['Gimnasio: pausa por viaje/lesión conservando la antigüedad'],
    notes: 'Conserva permanencia e historial; encadena a MEM-013 al reanudar.',
    config: {
      trigger: { type: 'EVENT', event: EV.MEMBERSHIP_SUSPENDED },
      variables: ['cliente.nombre', 'membresia.fechaReanudacion'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Confirmar suspensión',
          actions: [
            { type: ACTION_TYPES.FREEZE_MEMBERSHIP, params: {} },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Tu membresía está en pausa, {{cliente.nombre}}', body: 'Se reanudará el {{membresia.fechaReanudacion}}. Tu progreso queda guardado.' } },
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'membresia.suspendida' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'MEM-013',
    name: 'Reactivación de membresía suspendida',
    objective: 'Retomar la membresía tras una pausa y reenganchar al miembro.',
    problem: 'Las pausas se vuelven cancelaciones si no hay un buen reingreso.',
    whenToUse: 'Cuando llega la fecha de reanudación o el miembro reactiva.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: membresía reactivada'],
    conditions: ['Membresía en estado suspendida', 'Fecha de reanudación alcanzada'],
    variables: ['cliente.nombre', 'membresia.plan'],
    engines: ['rule', 'action', 'membership', 'benefit', 'analytics'],
    flow: ['Se reactiva la membresía', 'Se restablecen beneficios', 'Se da la bienvenida de regreso', 'Se registra'],
    actions: [ACTION_TYPES.ACTIVATE_MEMBERSHIP, ACTION_TYPES.SEND_PUSH, ACTION_TYPES.RECORD_HISTORY],
    esperas: [],
    events: [EV.MEMBERSHIP_REACTIVATED, EV.CLIENT_RECOVERED],
    exceptions: ['No estaba suspendida'],
    compatibleMembershipModels: [ANY],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: [],
    compatibleCampaigns: ['membresias', 'recuperacion'],
    dependencies: ['Membership Engine con reanudación'],
    compatibleTemplates: [],
    examples: ['“¡Bienvenido de vuelta! Tu membresía está activa otra vez”'],
    notes: 'Cierra el ciclo de pausa; refuerza el regreso con un pequeño beneficio.',
    config: {
      trigger: { type: 'EVENT', event: EV.MEMBERSHIP_REACTIVATED },
      variables: ['cliente.nombre', 'membresia.plan'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Reactivar y dar bienvenida',
          actions: [
            { type: ACTION_TYPES.ACTIVATE_MEMBERSHIP, params: { plan: '{{membresia.plan}}' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Bienvenido de vuelta, {{cliente.nombre}}!', body: 'Tu membresía está activa nuevamente.' } },
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'membresia.reactivada' } },
          ],
          chain: { event: EV.CLIENT_RECOVERED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-014',
    name: 'Expiración de membresía (cambio de estado)',
    objective: 'Gestionar el vencimiento: cambiar estado y ofrecer renovar.',
    problem: 'Membresías vencidas sin gestión pierden ingresos y datos de estado.',
    whenToUse: 'Cuando la membresía llega a su fecha de expiración sin renovar.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: membresía vencida'],
    conditions: ['Fecha de expiración alcanzada', 'Sin renovación'],
    variables: ['cliente.nombre', 'membresia.plan'],
    engines: ['rule', 'action', 'membership', 'benefit', 'promotion', 'analytics'],
    flow: ['Se detecta la expiración', 'Se cambia el estado a expirada', 'Se ofrece renovar con beneficio', 'Se registra en el historial'],
    actions: [ACTION_TYPES.RECORD_HISTORY, ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.APPLY_DISCOUNT_PERCENT],
    esperas: ['Oferta de renovación a 1 y 7 días de vencida (editable)'],
    events: [EV.MEMBERSHIP_EXPIRED, EV.CLIENT_RENEWED],
    exceptions: ['Ya renovó', 'Cancelación voluntaria previa'],
    compatibleMembershipModels: [ANY],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['RENEWAL', 'WINBACK'],
    compatibleCampaigns: ['membresias', 'recuperacion'],
    dependencies: ['Membership Engine con estado de expiración'],
    compatibleTemplates: [],
    examples: ['Plan vencido → estado “expirada” + oferta de reactivación'],
    notes: 'Encadena con la recuperación (E1.5) si no renueva; el cambio de estado lo hace el motor.',
    config: {
      trigger: { type: 'EVENT', event: EV.MEMBERSHIP_EXPIRED },
      variables: ['cliente.nombre', 'membresia.plan'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Registrar expiración y ofrecer renovar',
          actions: [
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'membresia.expirada' } },
            { type: ACTION_TYPES.APPLY_DISCOUNT_PERCENT, params: { percent: 20 } },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Tu membresía expiró, {{cliente.nombre}}', body: 'Reactívala con un beneficio especial.' } },
          ],
          chain: { event: EV.CLIENT_RENEWED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-015',
    name: 'Cancelación voluntaria (motivo + recuperación)',
    objective: 'Registrar el motivo, encuestar y activar recuperación.',
    problem: 'Cancelar sin aprender ni intentar retener pierde valor doble.',
    whenToUse: 'Cuando el miembro cancela voluntariamente.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: membresía cancelada'],
    conditions: ['Cancelación voluntaria'],
    variables: ['cliente.nombre', 'membresia.plan', 'cancelacion.motivo'],
    engines: ['rule', 'action', 'membership', 'benefit', 'campaign', 'analytics'],
    flow: ['Se registra la cancelación y su motivo', 'Encuesta breve', 'Beneficio/oferta de recuperación', 'Se inicia el journey de recuperación'],
    actions: [ACTION_TYPES.RECORD_HISTORY, ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.APPLY_BENEFIT],
    esperas: ['Oferta de recuperación a los 7 días (editable)'],
    events: [EV.MEMBERSHIP_CANCELLED, EV.CLIENT_FEEDBACK_GIVEN],
    exceptions: ['Cancelación por impago (usar MEM-016)', 'Opt-out de comunicaciones'],
    compatibleMembershipModels: [ANY],
    compatibleBenefits: ['CAR-011', 'CAR-004'],
    compatiblePromotions: ['WINBACK'],
    compatibleCampaigns: ['membresias', 'recuperacion'],
    dependencies: ['Membership Engine', 'Módulo de encuestas'],
    compatibleTemplates: [],
    examples: ['Cancela → “¿Por qué te vas?” + oferta de reingreso'],
    notes: 'Diferencia de la cancelación por impago; alimenta la recuperación (E1.5).',
    config: {
      trigger: { type: 'EVENT', event: EV.MEMBERSHIP_CANCELLED },
      variables: ['cliente.nombre', 'cancelacion.motivo'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Registrar y encuestar',
          actions: [
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'membresia.cancelada' } },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Lamentamos que te vayas, {{cliente.nombre}}', body: 'Cuéntanos por qué para mejorar.' } },
          ],
          wait: { ms: 604_800_000 },
          chain: { event: EV.CLIENT_FEEDBACK_GIVEN },
        },
        {
          label: 'Oferta de recuperación',
          actions: [{ type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-011' } }],
        },
      ],
    },
  }),

  pb({
    id: 'MEM-016',
    name: 'Cancelación por impago (dunning de membresía)',
    objective: 'Recuperar membresías perdidas por pagos fallidos.',
    problem: 'El churn involuntario por impago pierde ingresos evitables.',
    whenToUse: 'Cuando un cobro de la membresía falla.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: membresía vencida (por impago)'],
    conditions: ['Pago fallido', 'Membresía activa antes del fallo'],
    variables: ['cliente.nombre', 'membresia.plan'],
    engines: ['rule', 'action', 'membership', 'analytics'],
    flow: ['Se detecta el impago', 'Reintentos y avisos escalonados', 'Se facilita actualizar el pago', 'Al pagar, se reactiva'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.SEND_SMS, ACTION_TYPES.RENEW_MEMBERSHIP],
    esperas: ['Reintentos a 1, 3 y 7 días (editable)'],
    events: [EV.MEMBERSHIP_EXPIRED, EV.MEMBERSHIP_RENEWED],
    exceptions: ['Cancelación voluntaria', 'Método de pago eliminado'],
    compatibleMembershipModels: [M.SUBSCRIPTION_BOX, M.UNLIMITED, M.TIER, M.PREMIUM, M.VIP, M.CORPORATE, M.CUSTOM],
    compatibleBenefits: [],
    compatiblePromotions: ['RENEWAL'],
    compatibleCampaigns: ['membresias', 'recuperacion'],
    dependencies: ['Integración de cobros/reintentos', 'Membership Engine'],
    compatibleTemplates: [],
    examples: ['Tarjeta rechazada → secuencia de dunning específica de membresía'],
    notes: 'Churn involuntario: prioriza facilitar el pago; complementa REC-014 en clave de membresía.',
    config: {
      trigger: { type: 'EVENT', event: EV.MEMBERSHIP_EXPIRED },
      variables: ['cliente.nombre', 'membresia.plan'],
      channels: ['email', 'sms', 'push'],
      steps: [
        {
          label: 'Aviso de pago fallido',
          condition: 'membresia.motivoVencimiento == "pago_fallido"',
          actions: [{ type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'No pudimos procesar tu pago, {{cliente.nombre}}', body: 'Actualiza tu método para conservar tu {{membresia.plan}}.' } }],
          wait: { ms: 259_200_000 },
        },
        {
          label: 'Reintento final',
          condition: 'membresia.motivoVencimiento == "pago_fallido"',
          actions: [{ type: ACTION_TYPES.SEND_SMS, params: { body: 'Último aviso: actualiza tu pago para no perder tu membresía.' } }],
          chain: { event: EV.MEMBERSHIP_RENEWED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-017',
    name: 'Beneficios periódicos de membresía',
    objective: 'Entregar automáticamente los beneficios recurrentes del plan.',
    problem: 'Los beneficios periódicos no entregados reducen el valor percibido.',
    whenToUse: 'En cada ciclo (mensual/semanal) mientras la membresía esté activa.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado (ciclo del plan)'],
    conditions: ['Membresía activa', 'Corresponde entregar el beneficio del ciclo'],
    variables: ['cliente.nombre', 'membresia.plan'],
    engines: ['rule', 'action', 'membership', 'benefit', 'analytics'],
    flow: ['Comienza el ciclo', 'Se entrega el beneficio periódico', 'Se notifica', 'Se registra'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_PUSH],
    esperas: ['Según el ciclo del plan (editable)'],
    events: [EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Membresía inactiva', 'Beneficio ya entregado este ciclo'],
    compatibleMembershipModels: [M.UNLIMITED, M.SUBSCRIPTION_BOX, M.TIER, M.PREMIUM, M.VIP, M.LOYALTY, M.CORPORATE, M.CUSTOM],
    compatibleBenefits: ['CAR-004', 'CAR-011'],
    compatiblePromotions: [],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Membership Engine con beneficios por ciclo'],
    compatibleTemplates: [],
    examples: ['“Tu beneficio mensual está disponible”', 'Caja de suscripción del mes'],
    notes: 'La periodicidad se lee del plan; evita doble entrega por ciclo.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 9 1 * *' },
      variables: ['cliente.nombre', 'membresia.plan'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Entregar beneficio del ciclo',
          condition: 'membresia.estado == "activa"',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: '{{membresia.beneficioPeriodico}}' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Tu beneficio del mes, {{cliente.nombre}}', body: 'Ya está disponible. ¡Disfrútalo!' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-018',
    name: 'Beneficios por aniversario y permanencia',
    objective: 'Premiar la antigüedad del miembro para reforzar la lealtad.',
    problem: 'No reconocer la permanencia debilita el vínculo a largo plazo.',
    whenToUse: 'En el aniversario de la membresía o al cumplir hitos de permanencia.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Fecha: aniversario de membresía', 'Evento: hito de permanencia'],
    conditions: ['Membresía activa', 'Aniversario/hito alcanzado'],
    variables: ['cliente.nombre', 'membresia.mesesActivo'],
    engines: ['rule', 'action', 'membership', 'benefit', 'reward', 'analytics'],
    flow: ['Llega el aniversario/hito', 'Se entrega un beneficio de permanencia', 'Se felicita', 'Se registra'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.ADD_POINTS, ACTION_TYPES.SEND_PUSH],
    esperas: ['En la fecha del aniversario (editable)'],
    events: [EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Membresía inactiva'],
    compatibleMembershipModels: [ANY],
    compatibleBenefits: ['CAR-001', 'CAR-004'],
    compatiblePromotions: ['ANNIVERSARY', 'LOYALTY'],
    compatibleCampaigns: ['membresias', 'fidelizacion'],
    dependencies: ['Membership Engine con antigüedad'],
    compatibleTemplates: [],
    examples: ['“1 año contigo: un regalo por tu lealtad”', 'Beneficio a los 6/12/24 meses'],
    notes: 'Los hitos de permanencia y sus beneficios son editables; escalables por antigüedad.',
    config: {
      trigger: { type: 'DATE', params: { field: 'membresiaAniversario' } },
      variables: ['cliente.nombre', 'membresia.mesesActivo'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Premiar permanencia',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-001' } },
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 100 } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Gracias por {{membresia.mesesActivo}} meses, {{cliente.nombre}}!', body: 'Un regalo por tu lealtad.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-019',
    name: 'Beneficios por consumo y acumulativos',
    objective: 'Recompensar según el consumo del miembro con beneficios acumulativos.',
    problem: 'No premiar el consumo desaprovecha la motivación de usar más el plan.',
    whenToUse: 'Cuando el consumo alcanza umbrales configurables.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: uso de membresía / compra'],
    conditions: ['Consumo acumulado alcanza un umbral'],
    variables: ['cliente.nombre', 'membresia.consumoAcumulado'],
    engines: ['rule', 'action', 'membership', 'reward', 'benefit', 'analytics'],
    flow: ['Se acumula consumo', 'Al llegar al umbral, se libera un beneficio', 'Se reinicia/continúa la acumulación', 'Se registra'],
    actions: [ACTION_TYPES.ADD_POINTS, ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.CLIENT_REWARD_OBTAINED, EV.CLIENT_FREQUENCY_GOAL],
    exceptions: ['Umbral no alcanzado', 'Programa de consumo desactivado'],
    compatibleMembershipModels: [M.CREDITS, M.HYBRID, M.LOYALTY, M.REWARDS, M.PAY_PER_VISIT, M.PREPAID, M.CUSTOM],
    compatibleBenefits: ['CAR-001', 'CAR-004'],
    compatiblePromotions: ['CONSUMPTION', 'MILESTONE'],
    compatibleCampaigns: ['membresias', 'gamificacion'],
    dependencies: ['Membership/Reward Engine con acumulación por consumo'],
    compatibleTemplates: [],
    examples: ['“Acumulaste X consumos → beneficio desbloqueado”', 'Cashback por gasto acumulado'],
    notes: 'Los umbrales y beneficios acumulativos son editables; sirve para wallets y créditos.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_PURCHASE },
      variables: ['cliente.nombre', 'membresia.consumoAcumulado'],
      channels: ['push'],
      steps: [
        {
          label: 'Recompensa por consumo',
          condition: 'membresia.consumoAcumulado >= 500',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-001' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Beneficio desbloqueado, {{cliente.nombre}}!', body: 'Tu consumo acumulado te dio una recompensa.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'MEM-020',
    name: 'Recuperación de miembros (win-back de membresía)',
    objective: 'Recuperar exmiembros con una oferta de reingreso a la membresía.',
    problem: 'Los exmiembros son un activo desaprovechado si no se les reactiva.',
    whenToUse: 'Para miembros expirados/cancelados hace tiempo.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Segmento: exmiembro'],
    conditions: ['Membresía expirada/cancelada', 'Sin reingreso'],
    variables: ['cliente.nombre', 'membresia.planPrevio'],
    engines: ['rule', 'action', 'membership', 'benefit', 'promotion', 'campaign', 'analytics'],
    flow: ['Se identifica al exmiembro', 'Se envía oferta de reingreso', 'Al reactivar, se restablece el plan', 'Se mide'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.APPLY_DISCOUNT_PERCENT, ACTION_TYPES.ACTIVATE_MEMBERSHIP],
    esperas: ['Seguimiento a 30 y 60 días (editable)'],
    events: [EV.MEMBERSHIP_REACTIVATED, EV.CLIENT_RECOVERED],
    exceptions: ['Ya reingresó', 'Opt-out de comunicaciones'],
    compatibleMembershipModels: [ANY],
    compatibleBenefits: ['CAR-004', 'CAR-001'],
    compatiblePromotions: ['WINBACK', 'RENEWAL'],
    compatibleCampaigns: ['membresias', 'recuperacion'],
    dependencies: ['Membership Engine con estado previo del plan'],
    compatibleTemplates: [],
    examples: ['“Vuelve a tu membresía con una oferta de reingreso especial”'],
    notes: 'Cierra el ciclo de vida reconectando con exmiembros; combina con la recuperación (E1.5).',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'exmiembro' } },
      variables: ['cliente.nombre', 'membresia.planPrevio'],
      channels: ['email', 'whatsapp'],
      limits: { maxPerSubject: 2, perPeriod: 'YEAR' },
      steps: [
        {
          label: 'Oferta de reingreso',
          actions: [
            { type: ACTION_TYPES.APPLY_DISCOUNT_PERCENT, params: { percent: 30 } },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Vuelve a tu membresía, {{cliente.nombre}}', body: 'Tenemos una oferta especial para tu reingreso.' } },
          ],
          chain: { event: EV.MEMBERSHIP_REACTIVATED },
        },
      ],
    },
  }),
]

/** Lista mutable de los playbooks de membresías (para composición). */
export function membershipPlaybooks(): AutomationPlaybook[] {
  return [...MEMBERSHIP_PLAYBOOKS]
}

/** Busca un playbook de membresías por su ID (ej. "MEM-001"). */
export function getMembershipPlaybook(id: string): AutomationPlaybook | undefined {
  return MEMBERSHIP_PLAYBOOKS.find((p) => p.id === id)
}
