/**
 * Biblioteca de Automation Playbooks de REFERIDOS (Fase E1.7). Automatizan el
 * JOURNEY COMPLETO de un programa de referidos: código generado → compartido →
 * invitado registrado → primera conversión → validación antifraude → liberación
 * de recompensa → ranking → escalamiento → embajadores/influencers. NO
 * reimplementan el Referral Engine (que ya define lógica, reglas y recompensas):
 * lo operan y coordinan con el resto de motores. Funcionan con CUALQUIER modelo
 * de programa (clásico, ambos ganan, solo invitado, solo quien invita,
 * progresivo, embajadores, influencers, corporativo, empleados, equipos,
 * afiliados…). Un modelo futuro se integra por configuración.
 *
 * Estrategias probadas de referral (Dropbox/Uber/PayPal/marketplaces)
 * convertidas en playbooks UNIVERSALES instalables sobre el Automation Engine
 * (E1). Reutilizan Rule Engine (condiciones/antifraude), Action Engine
 * (acciones), el Referral Engine (estado/recompensas) y referencian Benefit/
 * Promotion/Membership/Reward/Campaign/Gamification/Analytics por código. La
 * recompensa por un referido puede activar cualquier otro motor existente.
 *
 * Cada Playbook es una automatización real (`config`) + su documentación
 * completa (25 apartados, incl. "Tipos de programas compatibles"). Nada
 * hardcodeado por modelo: recompensas/programas por variable/código.
 */

import { ACTION_TYPES } from '@/lib/rule-engine'
import { AUTOMATION_EVENTS as EV } from '../domain/events'
import { INDUSTRIES as I, REFERRAL_MODELS as R } from './types'
import type { AutomationPlaybook } from './types'

const U = I.UNIVERSAL
const ANY = R.ANY

// Configuración editable mínima (Documento Maestro): común a todos.
const EDITABLE = [
  'nombre', 'descripcion', 'triggers', 'reglas', 'recompensas', 'condiciones',
  'segmentos', 'prioridad', 'variables', 'horarios', 'canales', 'idioma',
  'limites', 'presupuesto', 'duracion', 'vigencia',
] as const

// KPIs típicos de programas de referidos.
const REF_KPIS = [
  'invitaciones_creadas', 'invitaciones_compartidas', 'tasa_conversion_referido',
  'referidos_registrados', 'referidos_convertidos', 'recompensas_liberadas',
  'fraude_detectado', 'valor_por_referido', 'embajadores_activos', 'roi_referidos',
  'tasa_apertura', 'tasa_clic',
] as const

/** Helper: completa los apartados comunes de un playbook de referidos. */
function pb(
  p: Omit<AutomationPlaybook, 'category' | 'editable' | 'kpis' | 'engines' | 'compatibleReferralModels'> &
    Partial<Pick<AutomationPlaybook, 'engines' | 'kpis' | 'editable' | 'compatibleReferralModels'>>,
): AutomationPlaybook {
  return {
    category: 'referidos',
    editable: p.editable ?? EDITABLE,
    kpis: p.kpis ?? REF_KPIS,
    engines: p.engines ?? ['rule', 'action', 'referral', 'analytics'],
    compatibleReferralModels: p.compatibleReferralModels ?? [ANY],
    ...p,
  }
}

export const REFERRAL_PLAYBOOKS: readonly AutomationPlaybook[] = [
  pb({
    id: 'REF-001',
    name: 'Código/enlace/QR de referido generado',
    objective: 'Activar al cliente para que comparta apenas obtiene su código.',
    problem: 'Muchos clientes generan el código pero nunca lo comparten.',
    whenToUse: 'Cuando el cliente obtiene su código/enlace/QR de referido.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: código de referido generado'],
    conditions: ['Código recién generado'],
    variables: ['cliente.nombre', 'referido.codigo'],
    engines: ['rule', 'action', 'referral', 'analytics'],
    flow: ['Se genera el código', 'Se registra el evento y estadística', 'Se invita a compartir con instrucciones claras'],
    actions: [ACTION_TYPES.RECORD_EVENT, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.REFERRAL_CODE_GENERATED, EV.REFERRAL_SHARED],
    exceptions: ['Programa de referidos inactivo'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['referidos'],
    dependencies: ['Referral Engine con programa activo'],
    compatibleTemplates: [],
    examples: ['“Tu código está listo: compártelo y ambos ganan”'],
    notes: 'Punto de entrada del journey; el código lo emite el Referral Engine.',
    config: {
      trigger: { type: 'EVENT', event: EV.REFERRAL_CODE_GENERATED },
      variables: ['cliente.nombre', 'referido.codigo'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Invitar a compartir',
          actions: [
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'referido.codigo_registrado' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Tu código está listo, {{cliente.nombre}}', body: 'Comparte {{referido.codigo}} y ambos ganan.' } },
          ],
          chain: { event: EV.REFERRAL_SHARED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-002',
    name: 'Invitación compartida (registrar canal y desempeño)',
    objective: 'Medir por dónde se comparte y reforzar los canales que convierten.',
    problem: 'Sin saber qué canal funciona, no se optimiza el programa.',
    whenToUse: 'Cuando el cliente comparte su invitación.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: invitación compartida'],
    conditions: ['Compartición registrada con canal'],
    variables: ['cliente.nombre', 'referido.canal'],
    engines: ['rule', 'action', 'referral', 'analytics'],
    flow: ['Se comparte la invitación', 'Se registra el canal', 'Se actualizan métricas', 'Se evalúa el desempeño del embajador'],
    actions: [ACTION_TYPES.RECORD_EVENT, ACTION_TYPES.INVOKE_MODULE],
    esperas: [],
    events: [EV.REFERRAL_SHARED],
    exceptions: ['Canal no soportado'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['referidos'],
    dependencies: ['Analytics con tracking de canales'],
    compatibleTemplates: [],
    examples: ['Comparte por WhatsApp vs redes → medir conversión por canal'],
    notes: 'Alimenta la analítica de canales; no molesta al usuario.',
    config: {
      trigger: { type: 'EVENT', event: EV.REFERRAL_SHARED },
      variables: ['cliente.nombre', 'referido.canal'],
      channels: ['inapp'],
      steps: [
        {
          label: 'Registrar canal y métricas',
          actions: [
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'referido.compartido_canal' } },
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'analytics', action: 'track_referral_channel' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'REF-003',
    name: 'Invitado registrado (validar e iniciar journey)',
    objective: 'Validar el registro del invitado y arrancar su journey de cliente.',
    problem: 'El invitado se registra pero no se le acompaña ni se valida el vínculo.',
    whenToUse: 'Cuando un invitado se registra con un código de referido.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: invitado registrado'],
    conditions: ['Registro con código válido', 'Requisitos del programa cumplidos'],
    variables: ['invitado.nombre', 'referido.codigo', 'cliente.nombre'],
    engines: ['rule', 'action', 'referral', 'campaign', 'analytics'],
    flow: ['El invitado se registra con código', 'Se valida el vínculo', 'Se actualiza el estado del referido', 'Se inicia el journey del nuevo cliente'],
    actions: [ACTION_TYPES.RECORD_EVENT, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.REFERRAL_REGISTERED, EV.CLIENT_REGISTERED],
    exceptions: ['Código inválido/expirado', 'Autoreferencia'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: [],
    compatibleCampaigns: ['referidos', 'onboarding'],
    dependencies: ['Referral Engine con vínculo referidor-invitado'],
    compatibleTemplates: [],
    examples: ['Invitado se registra → se le da la bienvenida y se avisa a quien invitó'],
    notes: 'Encadena con el onboarding (E1.2); la autoreferencia cae en excepción (antifraude).',
    config: {
      trigger: { type: 'EVENT', event: EV.REFERRAL_REGISTERED },
      variables: ['invitado.nombre', 'cliente.nombre'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Validar e iniciar journey',
          actions: [
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'referido.registro_validado' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Alguien usó tu invitación, {{cliente.nombre}}!', body: '{{invitado.nombre}} se registró. Cuando compre, ganas.' } },
          ],
          chain: { event: EV.CLIENT_REGISTERED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-004',
    name: 'Registro incompleto del invitado (recuperar)',
    objective: 'Recuperar invitados que abren la invitación pero no completan el registro.',
    problem: 'Se pierden referidos por fricción en el alta.',
    whenToUse: 'Cuando el invitado inicia y no termina el registro.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Segmento: invitado con registro incompleto'],
    conditions: ['Registro iniciado con código', 'No completado tras N tiempo'],
    variables: ['invitado.nombre', 'referido.codigo'],
    engines: ['rule', 'action', 'referral', 'campaign', 'analytics'],
    flow: ['Se detecta registro incompleto', 'Se recuerda completar con el incentivo del referido', 'Al completar, se emite evento'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.SEND_WHATSAPP],
    esperas: ['Recordatorio a 1h y 24h (editable)'],
    events: [EV.REFERRAL_REGISTERED],
    exceptions: ['Ya completó', 'Sin datos de contacto'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: [],
    compatibleCampaigns: ['referidos', 'conversion'],
    dependencies: ['Segmentación de registros incompletos'],
    compatibleTemplates: [],
    examples: ['“Estás a un paso de tu beneficio de bienvenida por invitación”'],
    notes: 'Reutiliza la lógica de recuperación de registro (ACQ-003) en clave de referido.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'invitado_incompleto' } },
      variables: ['invitado.nombre'],
      channels: ['email', 'whatsapp'],
      limits: { maxPerSubject: 2, perPeriod: 'WEEK' },
      steps: [
        {
          label: 'Recordar completar',
          actions: [{ type: ACTION_TYPES.SEND_WHATSAPP, params: { body: '{{invitado.nombre}}, completa tu registro y estrena tu beneficio de bienvenida.' } }],
          chain: { event: EV.REFERRAL_REGISTERED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-005',
    name: 'Primera conversión del referido (condición cumplida)',
    objective: 'Detectar la conversión del referido y disparar la recompensa.',
    problem: 'Si la conversión no se detecta, la recompensa nunca se libera.',
    whenToUse: 'Cuando el invitado cumple la condición del programa (ej. primera compra).',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: primera compra', 'Evento: referido convirtió'],
    conditions: ['El cliente fue referido', 'Cumple la condición configurada'],
    variables: ['invitado.nombre', 'cliente.nombre', 'referido.codigo'],
    engines: ['rule', 'action', 'referral', 'analytics'],
    flow: ['El referido cumple la condición', 'Se marca la conversión', 'Se pone la recompensa en estado pendiente (a validar)', 'Se registra'],
    actions: [ACTION_TYPES.RECORD_EVENT, ACTION_TYPES.INVOKE_MODULE],
    esperas: [],
    events: [EV.REFERRAL_CONVERTED, EV.REFERRAL_REWARD_PENDING],
    exceptions: ['No es referido', 'Condición no cumplida'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['referidos'],
    dependencies: ['Referral Engine con condición de conversión'],
    compatibleTemplates: [],
    examples: ['Referido hace su primera compra → recompensa pendiente de antifraude'],
    notes: 'Encadena a la validación antifraude (REF-006) antes de liberar.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_FIRST_PURCHASE },
      variables: ['cliente.nombre', 'referido.codigo'],
      channels: ['inapp'],
      steps: [
        {
          label: 'Marcar conversión y dejar pendiente',
          condition: 'cliente.referidoPor != null',
          actions: [
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'referido.convertido' } },
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'referral', action: 'mark_converted' } },
          ],
          chain: { event: EV.REFERRAL_REWARD_PENDING },
        },
      ],
    },
  }),

  pb({
    id: 'REF-006',
    name: 'Validación antifraude del referido',
    objective: 'Validar la conversión con reglas antifraude antes de recompensar.',
    problem: 'Los programas de referidos son un objetivo típico de fraude.',
    whenToUse: 'Cuando hay una recompensa pendiente de validar.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: recompensa pendiente'],
    conditions: ['Reglas antifraude del Rule Engine (identidad, duplicados, dispositivo, IP)'],
    variables: ['invitado.id', 'referido.codigo', 'invitado.ip', 'invitado.dispositivo'],
    engines: ['rule', 'action', 'referral', 'analytics'],
    flow: ['Recompensa pendiente', 'Se ejecutan reglas antifraude', 'Si pasa: liberar; si no: rechazar y auditar'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.RECORD_HISTORY],
    esperas: ['Ventana de validación configurable'],
    events: [EV.REFERRAL_REWARD_RELEASED, EV.REFERRAL_FRAUD_DETECTED],
    exceptions: ['Datos insuficientes para validar'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['referidos'],
    dependencies: ['Rule Engine con reglas antifraude', 'Referral Engine (antifraude toggleable)'],
    compatibleTemplates: [],
    examples: ['Misma IP/dispositivo/identidad → marcar sospechoso y no liberar'],
    notes: 'Reutiliza el antifraude del Referral Engine; toda decisión se audita.',
    config: {
      trigger: { type: 'EVENT', event: EV.REFERRAL_REWARD_PENDING },
      variables: ['referido.codigo', 'invitado.ip'],
      channels: ['inapp'],
      steps: [
        {
          label: 'Ejecutar antifraude',
          condition: 'referido.sospechoso == false',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'referral', action: 'validate_fraud' } },
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'referido.antifraude_ok' } },
          ],
          chain: { event: EV.REFERRAL_REWARD_RELEASED },
        },
        {
          label: 'Marcar fraude',
          condition: 'referido.sospechoso == true',
          actions: [
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'referido.antifraude_bloqueado' } },
          ],
          chain: { event: EV.REFERRAL_FRAUD_DETECTED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-007',
    name: 'Liberación de recompensa (ambas partes)',
    objective: 'Liberar las recompensas del programa y activar otros motores.',
    problem: 'Sin liberación automática, la promesa del referido se incumple.',
    whenToUse: 'Cuando la conversión pasó el antifraude.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: recompensa liberada'],
    conditions: ['Antifraude aprobado', 'Recompensa según el modelo del programa'],
    variables: ['cliente.nombre', 'invitado.nombre', 'referido.recompensa'],
    engines: ['rule', 'action', 'referral', 'benefit', 'reward', 'membership', 'analytics'],
    flow: ['Se aprueba la conversión', 'Se libera la recompensa según el target del modelo', 'Se activan otros motores (benefit/points/membership)', 'Se actualiza el ranking'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.REFERRAL_REWARD_RELEASED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Recompensa ya liberada', 'Presupuesto agotado'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: ['CAR-004', 'CAR-001'],
    compatiblePromotions: [],
    compatibleCampaigns: ['referidos'],
    dependencies: ['Referral Engine (puente a Benefit Engine ya existente)'],
    compatibleTemplates: [],
    examples: ['Ambos ganan → beneficio a ambos; solo invitado → beneficio al invitado'],
    notes: 'El target (ambos/referidor/invitado) lo define el modelo; la recompensa puede ser beneficio, puntos o membresía.',
    config: {
      trigger: { type: 'EVENT', event: EV.REFERRAL_REWARD_RELEASED },
      variables: ['cliente.nombre', 'invitado.nombre'],
      channels: ['push', 'whatsapp'],
      steps: [
        {
          label: 'Liberar y notificar',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'referral', action: 'release_rewards' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Recompensa liberada, {{cliente.nombre}}!', body: 'Tú y {{invitado.nombre}} ya tienen su premio.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-008',
    name: 'Recompensa de referido pendiente (recordatorio)',
    objective: 'Empujar hacia la conversión cuando la recompensa está a punto.',
    problem: 'Muchas recompensas quedan pendientes porque falta un último paso.',
    whenToUse: 'Cuando el referido se registró pero aún no convierte.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Segmento: referido registrado sin convertir'],
    conditions: ['Referido registrado', 'Sin cumplir la condición'],
    variables: ['invitado.nombre', 'cliente.nombre', 'referido.condicion'],
    engines: ['rule', 'action', 'referral', 'benefit', 'analytics'],
    flow: ['Se detecta conversión pendiente', 'Se recuerda al invitado el beneficio por convertir', 'Al convertir, se emite evento'],
    actions: [ACTION_TYPES.SEND_WHATSAPP, ACTION_TYPES.SEND_PUSH],
    esperas: ['Recordatorios a 2 y 5 días (editable)'],
    events: [EV.REFERRAL_CONVERTED],
    exceptions: ['Ya convirtió', 'Programa finalizado'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: [],
    compatibleCampaigns: ['referidos', 'conversion'],
    dependencies: ['Referral Engine con estado de conversión'],
    compatibleTemplates: [],
    examples: ['“Haz tu primera compra y desbloquea tu beneficio de bienvenida”'],
    notes: 'Empuja al invitado; también se puede avisar a quien invitó para reactivar.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'referido_sin_convertir' } },
      variables: ['invitado.nombre'],
      channels: ['whatsapp', 'push'],
      limits: { maxPerSubject: 2, perPeriod: 'WEEK' },
      steps: [
        {
          label: 'Empujar conversión',
          actions: [{ type: ACTION_TYPES.SEND_WHATSAPP, params: { body: '{{invitado.nombre}}, completa tu primera compra y estrena tu beneficio.' } }],
          chain: { event: EV.REFERRAL_CONVERTED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-009',
    name: 'Recompensa de referido por vencer/vencida',
    objective: 'Evitar que las recompensas de referido caduquen sin usarse.',
    problem: 'Las recompensas vencidas frustran y reducen la confianza en el programa.',
    whenToUse: 'Cuando una recompensa de referido está por vencer o venció.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: recompensa por vencer', 'Evento: recompensa vencida'],
    conditions: ['Recompensa liberada no usada', 'Próxima a expirar o expirada'],
    variables: ['cliente.nombre', 'referido.diasRestantes'],
    engines: ['rule', 'action', 'referral', 'benefit', 'analytics'],
    flow: ['Se detecta la expiración', 'Recordatorio', 'Extensión o alternativa según reglas', 'Al usar, se registra'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.UPDATE_BENEFIT],
    esperas: ['Recordatorio 48h y 24h antes (editable)'],
    events: [EV.REFERRAL_REWARD_EXPIRED, EV.CLIENT_COUPON_USED],
    exceptions: ['Ya usada', 'Extensión no permitida'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: ['CAR-004', 'CAR-011'],
    compatiblePromotions: ['REMINDER'],
    compatibleCampaigns: ['referidos'],
    dependencies: ['Referral/Benefit Engine con expiración de recompensa'],
    compatibleTemplates: [],
    examples: ['“Tu recompensa por invitar expira en 2 días”'],
    notes: 'Reutiliza el rescate de beneficios (REC-006) para recompensas de referido.',
    config: {
      trigger: { type: 'EVENT', event: EV.BENEFIT_EXPIRING },
      variables: ['cliente.nombre', 'referido.diasRestantes'],
      channels: ['push', 'whatsapp'],
      steps: [
        {
          label: 'Recordar/extender recompensa',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Tu recompensa expira pronto', body: '{{cliente.nombre}}, te quedan {{referido.diasRestantes}} días.' } },
            { type: ACTION_TYPES.UPDATE_BENEFIT, params: { extendDays: 3 } },
          ],
          chain: { event: EV.CLIENT_COUPON_USED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-010',
    name: 'Fraude detectado / referido rechazado',
    objective: 'Gestionar los referidos marcados por antifraude sin recompensarlos.',
    problem: 'Recompensar referidos fraudulentos erosiona el presupuesto y el programa.',
    whenToUse: 'Cuando el antifraude marca un referido como sospechoso/rechazado.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: fraude detectado', 'Evento: referido rechazado'],
    conditions: ['Referido marcado como sospechoso por el Rule Engine'],
    variables: ['referido.codigo', 'invitado.id', 'fraude.motivo'],
    engines: ['rule', 'action', 'referral', 'analytics'],
    flow: ['Se marca el fraude', 'Se bloquea la recompensa', 'Se audita el caso', 'Opcional: alerta al equipo'],
    actions: [ACTION_TYPES.RECORD_HISTORY, ACTION_TYPES.SEND_INTERNAL_NOTIFICATION],
    esperas: [],
    events: [EV.REFERRAL_FRAUD_DETECTED, EV.REFERRAL_REJECTED],
    exceptions: ['Falso positivo (revisión manual)'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['referidos'],
    dependencies: ['Rule Engine antifraude', 'Auditoría'],
    compatibleTemplates: [],
    examples: ['Duplicado por dispositivo → rechazar y registrar evidencia'],
    notes: 'Nunca libera recompensa; deja auditoría completa y permite revisión manual.',
    config: {
      trigger: { type: 'EVENT', event: EV.REFERRAL_FRAUD_DETECTED },
      variables: ['referido.codigo', 'fraude.motivo'],
      channels: ['inapp'],
      steps: [
        {
          label: 'Bloquear y auditar',
          actions: [
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'referido.fraude_auditado' } },
            { type: ACTION_TYPES.SEND_INTERNAL_NOTIFICATION, params: { title: 'Referido sospechoso', body: 'Código {{referido.codigo}} marcado: {{fraude.motivo}}.' } },
          ],
          chain: { event: EV.REFERRAL_REJECTED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-011',
    name: 'Escalamiento de niveles (programa progresivo)',
    objective: 'Subir de categoría y asignar beneficios al alcanzar hitos de referidos.',
    problem: 'Sin niveles visibles, quien refiere pierde motivación.',
    whenToUse: 'Cuando el referidor alcanza nuevos hitos de conversiones.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: recompensa liberada', 'Segmento: alcanzó hito de referidos'],
    conditions: ['Nº de referidos convertidos == hito del programa'],
    variables: ['cliente.nombre', 'referido.totalConvertidos', 'referido.nivel'],
    engines: ['rule', 'action', 'referral', 'benefit', 'gamification', 'campaign', 'analytics'],
    flow: ['Se alcanza un hito', 'Se actualiza la categoría', 'Se asignan beneficios del nivel', 'Se inician nuevas campañas'],
    actions: [ACTION_TYPES.UPDATE_MEMBERSHIP_LEVEL, ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.CLIENT_LEVEL_UP, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Hito no configurado', 'Programa no progresivo'],
    compatibleReferralModels: [R.PROGRESSIVE, R.AMBASSADOR, R.INFLUENCER, R.TEAM, R.CORPORATE],
    compatibleBenefits: ['CAR-001', 'CAR-004'],
    compatiblePromotions: ['MILESTONE'],
    compatibleCampaigns: ['referidos', 'gamificacion'],
    dependencies: ['Referral Engine con niveles progresivos', 'Gamification Engine'],
    compatibleTemplates: [],
    examples: ['3 referidos → nivel plata; 10 → oro con más beneficios'],
    notes: 'Los hitos y beneficios por nivel son editables; aplica a modelos progresivos.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'referidor_hito' } },
      variables: ['cliente.nombre', 'referido.totalConvertidos'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Escalar nivel',
          condition: 'referido.totalConvertidos >= 3',
          actions: [
            { type: ACTION_TYPES.UPDATE_MEMBERSHIP_LEVEL, params: { level: 'referidor_plata' } },
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-001' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Subiste de nivel, {{cliente.nombre}}!', body: 'Ya convertiste {{referido.totalConvertidos}} referidos.' } },
          ],
          chain: { event: EV.CLIENT_LEVEL_UP },
        },
      ],
    },
  }),

  pb({
    id: 'REF-012',
    name: 'Detección e invitación de embajadores',
    objective: 'Detectar clientes de alto rendimiento e invitarlos al programa de embajadores.',
    problem: 'Los mejores referidores no se identifican ni se potencian.',
    whenToUse: 'Cuando un cliente supera el umbral de desempeño de referidos.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: embajador detectado'],
    conditions: ['Desempeño de referidos por encima del umbral'],
    variables: ['cliente.nombre', 'referido.totalConvertidos'],
    engines: ['rule', 'action', 'referral', 'benefit', 'membership', 'campaign', 'analytics'],
    flow: ['Se detecta alto desempeño', 'Se invita al programa de embajadores', 'Se asignan beneficios permanentes', 'Se registra'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.RECORD_EVENT],
    esperas: [],
    events: [EV.REFERRAL_AMBASSADOR_REACHED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Ya es embajador', 'Programa de embajadores desactivado'],
    compatibleReferralModels: [R.AMBASSADOR, R.PROGRESSIVE, R.INFLUENCER],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['AMBASSADOR'],
    compatibleCampaigns: ['referidos', 'embajadores'],
    dependencies: ['Referral Engine con programa de embajadores'],
    compatibleTemplates: [],
    examples: ['Cliente con 10 conversiones → invitación a embajador con beneficios VIP'],
    notes: 'Los embajadores reciben beneficios permanentes según el Referral Engine.',
    config: {
      trigger: { type: 'EVENT', event: EV.REFERRAL_AMBASSADOR_REACHED },
      variables: ['cliente.nombre', 'referido.totalConvertidos'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Invitar a embajador',
          actions: [
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Eres de los mejores, {{cliente.nombre}}', body: 'Te invitamos a nuestro programa de embajadores con beneficios exclusivos.' } },
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-001' } },
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'embajador.invitado' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-013',
    name: 'Campañas de influencers',
    objective: 'Gestionar campañas de influencers midiendo conversiones y ajustando recompensas.',
    problem: 'Las campañas de influencers sin medición no escalan ni se optimizan.',
    whenToUse: 'Para participantes tipo influencer con enlaces de campaña.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (medición de campaña)', 'Segmento: influencers activos'],
    conditions: ['Participante influencer', 'Campaña activa'],
    variables: ['cliente.nombre', 'campana.conversiones'],
    engines: ['rule', 'action', 'referral', 'campaign', 'analytics'],
    flow: ['Se mide la conversión de la campaña', 'Se ajustan las recompensas por desempeño', 'Se comunica el avance', 'Se registra'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Medición periódica (editable)'],
    events: [EV.REFERRAL_REWARD_RELEASED, EV.AUTOMATION_FINISHED],
    exceptions: ['Campaña finalizada', 'Sin conversiones'],
    compatibleReferralModels: [R.INFLUENCER, R.AMBASSADOR],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['INFLUENCER'],
    compatibleCampaigns: ['referidos', 'influencers'],
    dependencies: ['Referral Engine (modelo influencer)', 'Campaign Engine'],
    compatibleTemplates: [],
    examples: ['Influencer con enlace propio → recompensa según conversiones medidas'],
    notes: 'El modelo influencer no exige compras frecuentes; la empresa define conversiones mínimas.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 9 * * 1' },
      variables: ['cliente.nombre', 'campana.conversiones'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Medir y ajustar recompensa',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'referral', action: 'settle_influencer_rewards' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Tu campaña avanza, {{cliente.nombre}}', body: 'Llevas {{campana.conversiones}} conversiones.' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'REF-014',
    name: 'Programas corporativos / empresas afiliadas',
    objective: 'Automatizar referidos entre empresas, flotas y afiliados.',
    problem: 'Los acuerdos B2B/afiliados no se operan sin automatización dedicada.',
    whenToUse: 'Para programas corporativos, de empleados, equipos o afiliados.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: referido convirtió (programa corporativo)'],
    conditions: ['Participante corporativo/afiliado', 'Conversión válida'],
    variables: ['empresa.nombre', 'referido.totalConvertidos'],
    engines: ['rule', 'action', 'referral', 'benefit', 'campaign', 'analytics'],
    flow: ['Conversión en programa corporativo', 'Se acreditan recompensas/comisiones al afiliado', 'Se actualiza el tablero', 'Se registra'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.RECORD_HISTORY],
    esperas: ['Liquidación periódica (editable)'],
    events: [EV.REFERRAL_REWARD_RELEASED, EV.AUTOMATION_FINISHED],
    exceptions: ['Fuera del acuerdo', 'Programa suspendido'],
    compatibleReferralModels: [R.CORPORATE, R.EMPLOYEE, R.TEAM],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['CORPORATE'],
    compatibleCampaigns: ['referidos', 'alianzas'],
    dependencies: ['Referral Engine (modelos corporativos)'],
    compatibleTemplates: [],
    examples: ['Flota que refiere flotas', 'Empleados que refieren clientes con comisión'],
    notes: 'Comisiones/recompensas y liquidación según el acuerdo; todo configurable.',
    config: {
      trigger: { type: 'EVENT', event: EV.REFERRAL_CONVERTED },
      variables: ['empresa.nombre', 'referido.totalConvertidos'],
      channels: ['email'],
      steps: [
        {
          label: 'Acreditar al afiliado',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'referral', action: 'settle_corporate_rewards' } },
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'referido.corporativo_liquidado' } },
          ],
          chain: { event: EV.REFERRAL_REWARD_RELEASED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-015',
    name: 'Ranking y competencias de referidos',
    objective: 'Mantener un ranking y lanzar competencias para estimular referidos.',
    problem: 'La competitividad sana multiplica los referidos si se hace visible.',
    whenToUse: 'De forma recurrente o durante una competencia.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado (actualización de ranking)'],
    conditions: ['Programa con ranking/competencia activo'],
    variables: ['cliente.nombre', 'referido.posicionRanking'],
    engines: ['rule', 'action', 'referral', 'gamification', 'campaign', 'analytics'],
    flow: ['Se actualiza el ranking', 'Se comunica la posición y premios', 'Se motiva a subir', 'Al cierre, se premia a los primeros'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Actualización periódica (editable)'],
    events: [EV.CLIENT_REWARD_OBTAINED, EV.AUTOMATION_FINISHED],
    exceptions: ['Sin competencia activa'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['CONTEST'],
    compatibleCampaigns: ['referidos', 'gamificacion'],
    dependencies: ['Referral/Gamification Engine con ranking'],
    compatibleTemplates: [],
    examples: ['“Vas #4 esta semana: 2 referidos más y entras al podio”'],
    notes: 'El ranking lo mantiene el Referral/Gamification Engine; la competencia es editable.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 18 * * 5' },
      variables: ['cliente.nombre', 'referido.posicionRanking'],
      channels: ['push'],
      steps: [
        {
          label: 'Comunicar ranking',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'referral', action: 'update_ranking' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Vas #{{referido.posicionRanking}}, {{cliente.nombre}}', body: 'Sube posiciones invitando a más amigos.' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'REF-016',
    name: 'Bonificaciones temporales y eventos especiales',
    objective: 'Multiplicar referidos con boosts por tiempo limitado.',
    problem: 'Los programas se estancan sin picos de incentivo.',
    whenToUse: 'Durante eventos especiales o ventanas de bonificación.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado (ventana de bonificación)'],
    conditions: ['Bonificación temporal activa'],
    variables: ['cliente.nombre', 'bono.multiplicador'],
    engines: ['rule', 'action', 'referral', 'promotion', 'campaign', 'analytics'],
    flow: ['Comienza la ventana de bono', 'Se comunica el multiplicador', 'Las conversiones valen más', 'Al cerrar, se liquidan'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.INVOKE_MODULE],
    esperas: ['Duración de la bonificación (editable)'],
    events: [EV.REFERRAL_REWARD_RELEASED, EV.AUTOMATION_FINISHED],
    exceptions: ['Fuera de la ventana'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['BONUS', 'SEASONAL'],
    compatibleCampaigns: ['referidos', 'estacional'],
    dependencies: ['Referral Engine con multiplicadores temporales'],
    compatibleTemplates: [],
    examples: ['“Este fin de semana tus referidos valen doble”'],
    notes: 'El multiplicador y la vigencia son editables; ideal para fechas clave.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 10 * * 6' },
      variables: ['cliente.nombre', 'bono.multiplicador'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Anunciar bono temporal',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Referidos x{{bono.multiplicador}}!', body: '{{cliente.nombre}}, invita ahora y gana más.' } },
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'referral', action: 'apply_temporary_boost' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'REF-017',
    name: 'Programas estacionales de referidos',
    objective: 'Lanzar campañas de referido atadas a temporadas y fechas clave.',
    problem: 'No aprovechar la estacionalidad desperdicia demanda natural.',
    whenToUse: 'En temporadas, festivos o eventos del calendario.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado por temporada/fecha'],
    conditions: ['Temporada activa', 'Programa de referidos habilitado'],
    variables: ['cliente.nombre', 'temporada.nombre'],
    engines: ['rule', 'action', 'referral', 'promotion', 'campaign', 'analytics'],
    flow: ['Llega la temporada', 'Se lanza la campaña de referido estacional', 'Se comunica el incentivo especial', 'Se mide'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.SEND_PUSH],
    esperas: ['Según calendario de temporada (editable)'],
    events: [EV.REFERRAL_SHARED, EV.AUTOMATION_FINISHED],
    exceptions: ['Fuera de temporada'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['SEASONAL'],
    compatibleCampaigns: ['referidos', 'estacional'],
    dependencies: ['Calendario estacional', 'Referral Engine'],
    compatibleTemplates: [],
    examples: ['Campaña de referido navideña / de aniversario del negocio'],
    notes: 'Usa SCHEDULE; el incentivo y el calendario son editables.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 9 1 12 *', params: { season: 'editable' } },
      variables: ['cliente.nombre', 'temporada.nombre'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Lanzar campaña estacional',
          actions: [{ type: ACTION_TYPES.SEND_PUSH, params: { title: 'Referidos de {{temporada.nombre}}', body: '{{cliente.nombre}}, invita en esta temporada y gana más.' } }],
          chain: { event: EV.REFERRAL_SHARED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-018',
    name: 'Reactivación de referidores inactivos',
    objective: 'Volver a activar a quienes refirieron antes y ya no lo hacen.',
    problem: 'Los referidores que se enfrían dejan de traer clientes de bajo costo.',
    whenToUse: 'Cuando un buen referidor lleva tiempo sin invitar.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Segmento: referidor inactivo'],
    conditions: ['Refirió antes', 'Sin invitaciones recientes'],
    variables: ['cliente.nombre', 'referido.codigo'],
    engines: ['rule', 'action', 'referral', 'benefit', 'campaign', 'analytics'],
    flow: ['Se detecta al referidor inactivo', 'Se le recuerda su código con un incentivo', 'Al compartir, se emite evento'],
    actions: [ACTION_TYPES.SEND_WHATSAPP, ACTION_TYPES.APPLY_BENEFIT],
    esperas: ['Reactivación tras N días sin invitar (editable)'],
    events: [EV.REFERRAL_SHARED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Nunca refirió', 'Programa inactivo'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: [],
    compatibleCampaigns: ['referidos', 'recuperacion'],
    dependencies: ['Referral Engine con historial de invitaciones'],
    compatibleTemplates: [],
    examples: ['“Hace tiempo no invitas: comparte hoy y gana un extra”'],
    notes: 'Combina el journey de referidos con la lógica de recuperación (E1.5).',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'referidor_inactivo' } },
      variables: ['cliente.nombre', 'referido.codigo'],
      channels: ['whatsapp', 'push'],
      limits: { maxPerSubject: 1, perPeriod: 'MONTH' },
      steps: [
        {
          label: 'Reactivar referidor',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-004' } },
            { type: ACTION_TYPES.SEND_WHATSAPP, params: { body: '{{cliente.nombre}}, comparte tu código {{referido.codigo}} hoy y gana un beneficio extra.' } },
          ],
          chain: { event: EV.REFERRAL_SHARED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-019',
    name: 'Agradecimiento y refuerzo tras cada referido exitoso',
    objective: 'Reforzar el comportamiento agradeciendo cada conversión lograda.',
    problem: 'Sin refuerzo, incluso los buenos referidores pierden motivación.',
    whenToUse: 'Cada vez que un referido del cliente convierte.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: recompensa liberada'],
    conditions: ['El referidor logró una conversión'],
    variables: ['cliente.nombre', 'invitado.nombre'],
    engines: ['rule', 'action', 'referral', 'gamification', 'analytics'],
    flow: ['Se libera una recompensa', 'Se agradece al referidor', 'Se muestra su progreso', 'Se invita a repetir'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.ADD_POINTS],
    esperas: [],
    events: [EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Recompensa no liberada'],
    compatibleReferralModels: [ANY],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: [],
    compatibleCampaigns: ['referidos', 'fidelizacion'],
    dependencies: ['Referral Engine'],
    compatibleTemplates: [],
    examples: ['“¡Gracias! {{invitado.nombre}} ya es cliente. Invita a otro y gana más”'],
    notes: 'Refuerzo positivo inmediato; incrementa la tasa de referidos repetidos.',
    config: {
      trigger: { type: 'EVENT', event: EV.REFERRAL_REWARD_RELEASED },
      variables: ['cliente.nombre', 'invitado.nombre'],
      channels: ['push'],
      steps: [
        {
          label: 'Agradecer y motivar',
          actions: [
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 20 } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Gracias, {{cliente.nombre}}!', body: '{{invitado.nombre}} ya es cliente. Invita a otro y gana más.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'REF-020',
    name: 'Alianzas comerciales (co-referido entre negocios)',
    objective: 'Automatizar referidos cruzados entre negocios aliados.',
    problem: 'Las alianzas de referido cruzado no se operan sin automatización.',
    whenToUse: 'Cuando existe un acuerdo de referido con negocios aliados.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: referido convirtió (alianza)'],
    conditions: ['Referido proveniente de un aliado', 'Conversión válida'],
    variables: ['aliado.nombre', 'cliente.nombre'],
    engines: ['rule', 'action', 'referral', 'benefit', 'campaign', 'analytics'],
    flow: ['Conversión de referido de alianza', 'Se acredita al aliado y/o al cliente', 'Se actualiza el tablero conjunto', 'Se registra'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.RECORD_HISTORY],
    esperas: ['Liquidación entre aliados (editable)'],
    events: [EV.REFERRAL_REWARD_RELEASED, EV.AUTOMATION_FINISHED],
    exceptions: ['Fuera del acuerdo de alianza'],
    compatibleReferralModels: [R.CORPORATE, R.TEAM, R.CLASSIC, R.BOTH],
    compatibleBenefits: ['CAR-004', 'CAR-001'],
    compatiblePromotions: ['ALLIANCE'],
    compatibleCampaigns: ['referidos', 'alianzas'],
    dependencies: ['Referral Engine con soporte de aliados'],
    compatibleTemplates: [],
    examples: ['Car Wash y taller aliado se refieren clientes mutuamente'],
    notes: 'Las reglas de acreditación entre aliados son configurables; reutiliza el Referral Engine.',
    config: {
      trigger: { type: 'EVENT', event: EV.REFERRAL_CONVERTED },
      variables: ['aliado.nombre', 'cliente.nombre'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Acreditar alianza',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'referral', action: 'settle_alliance_rewards' } },
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-004' } },
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'referido.alianza_liquidada' } },
          ],
          chain: { event: EV.REFERRAL_REWARD_RELEASED },
        },
      ],
    },
  }),
]

/** Lista mutable de los playbooks de referidos (para composición). */
export function referralPlaybooks(): AutomationPlaybook[] {
  return [...REFERRAL_PLAYBOOKS]
}

/** Busca un playbook de referidos por su ID (ej. "REF-001"). */
export function getReferralPlaybook(id: string): AutomationPlaybook | undefined {
  return REFERRAL_PLAYBOOKS.find((p) => p.id === id)
}
